### ISSUE TITLE
Failed to replace object: PersistentVolumeClaim when upgrading from helm v3.1.1 to v3.9.4

### ISSUE THREAD

**Issue by cretzel** [helm/helm#11729]
I want to upgrade from helm v3.1.1 to v3.9.4, but helm upgrade fails on a PVC with the new version. Target platform is Azure AKS.

```
client.go:261: [debug] error updating the resource "loki-claim": failed to replace object: PersistentVolumeClaim "loki-claim" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
      AccessModes:      {"ReadWriteOnce"},
      Selector:         nil,
      Resources:        {Requests: {s"storage": {i: {...}, s: "64G", Format: "DecimalSI"}}},
-     VolumeName:       "pvc-55f471bc-8587-43c9-b4f7-d558510a85e5",
+     VolumeName:       "",
      StorageClassName: &"default",
      VolumeMode:       &"Filesystem",
      ... // 2 identical fields
  }
```

The template looks like this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: loki
    component: "loki"
    release: monitoring
  name: loki-claim
  namespace: management
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "64G"
  storageClassName: default
```

Output of `helm version`:
We are upgrading from v3.1.1
`version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}`
to v.3.9.4:
`version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Azure AKS

I found similar issues but they were mostly related to the storageClassName. It seems this is only related to the VolumeName. Any ideas?

**Comment by joejulian** [comment]
This seems to be an issue with your template. "Forbidden: spec is immutable after creation except resources.requests for bound claims" is a Kubernetes restriction. Your template is trying to replace the configured `VolumeName` with an empty string. Maybe delete that key from your template.

**Comment by cretzel** [comment]
> This seems to be an issue with your template. "Forbidden: spec is immutable after creation except resources.requests for bound claims" is a Kubernetes restriction. Your template is trying to replace the configured `VolumeName` with an empty string. Maybe delete that key from your template.

Thanks for the reply. But the key "volumeName" is not specified in my template.

**Comment by joejulian** [comment]
Well then there's not enough information to support this question. Please provide a minimal repro.

**Comment by cretzel** [comment]
While setting up a minimal repro (see https://github.com/cretzel/helm-11729) we found out that the issue is somehow related to the `--force` flag. We are deploying the chart like this

```
helm upgrade example example/ --install --force
```

This works with helm v3.1.1. But with helm v3.9.4 we get the error mentioned above. Without the `--force` flag it also works with v3.9.4.

**Comment by joejulian** [comment]
Ah, yes. The force flag uses the cli-runtime to do a server-side replace. The api server ensures that the replacement doesn't break the resource and, replacing a pvc spec that has a volumeName with one without it would break the pvc.

Helm is working as intended, as is the api server.

I'm not sure you need `--force`. Have you tried `--reset-values`? I think this will get the behavior you're looking for.

**Comment by joejulian** [comment]
btw... the reason it worked with 3.1 is it deleted the PVC and created a new one. I wonder how many times someone asked, "why do we have so many unbound PVs?"

**Comment by cretzel** [comment]
Okay, thanks a lot @joejulian. We will try to remove the `--force` flag to fix this. 

> btw... the reason it worked with 3.1 is it deleted the PVC and created a new one. I wonder how many times someone asked, "why do we have so many unbound PVs?"

With 3.1 we don't see any PVCs recreated or any unbound PVs.

**Comment by Esimseitm** [comment]
Hello! Tell me how is this problem solved at the moment? Is it possible to somehow pass the --force flag to the old names Volume Name and Storage Name so that it is recreated to exactly the same or the same.

**Comment by ElSamhaa** [comment]
After a lot of search in the helm issues and discussions, still the same old issue when using `--force`. `--reuse-values` doesn't help too.
I believe there should be a way to treat PVCs differently or provide an annotation that can do so.
