### ISSUE TITLE
--set parses number only values as float64

### ISSUE THREAD

**Issue by databus23** [helm/helm#1707]
I just noticed that something like `helm install --set tag=20161216` ends up in scientific notation in the template and thats because `{{ typeOf .Value.tag }}` yields `float64`.

Thats even true for small integers like `helm install --set tag=1` --> `float64`.

This is happening with helm 2.1.0

**Comment by technosophos** [comment]
Does it work differently if you do `--set tag=\"1\"`?

**Comment by technosophos** [comment]
Thanks to @chancez we know the exact problem: During the conversions to and from JSON done by `ghodss/yaml`, integers are being cast into float64s to represent Javascript's numeric type. This is causing all integers above a certain value to be represented in scientific notation.

**Comment by ipedrazas** [comment]
I've been bitten by the same problem. The way of getting over the hump (or the bug) is to do this:

`--set bignumber=\\"a185576882739235744\\"`

**Comment by technosophos** [comment]
Another workaround we have used is to do stuff like this:

```
--set port=":1234567"
```

Then in the template:

```
{{ .Values.port | replace ":" "" }}
```

**Comment by databus23** [comment]
Yuck! 😷

**Comment by jemc** [comment]
This is a heck of a pain, and @ipedrazas' workaround doesn't seem to work for me, or any other style of quoting I've tried.

I'm not quite willing yet to swallow my pride and try @technosophos' ugly hack...

**Comment by Smana** [comment]
I'm facing the same issue from time to time for the image tag.
I'll try to use one of these workaround. I hope it will be fixed soon :)

**Comment by holybit** [comment]
In my case, seeing this below on `--set image.tag=5997578`:

```bash
$ kubetctl describe po msj-treasure-map-msj-treasure-map-192172122-dnb80
...
Events:
  Type     Reason         Age               From                                    Message
  ----     ------         ----              ----                                    -------
  Normal   Scheduled      1m                default-scheduler                       Successfully assigned msj-treasure-map-msj-treasure-map-192172122-dnb80 to ip-10-253-13-113.ec2.internal
  Warning  InspectFailed  15s (x9 over 1m)  kubelet, ip-10-253-13-113.ec2.internal  Failed to apply default image tag "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06": couldn't parse image reference "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06": invalid reference format
  Warning  InspectFailed  15s (x9 over 1m)  kubelet, ip-10-253-13-113.ec2.internal  Failed to apply default image tag "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06": couldn't parse image reference "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06": invalid reference format
  Warning  FailedSync     15s (x9 over 1m)  kubelet, ip-10-253-13-113.ec2.internal  Error syncing pod, skipping: [failed to "StartContainer" for "msj-treasure-map-uwsgi" with InvalidImageName: "Failed to apply default image tag \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06\": couldn't parse image reference \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06\": invalid reference format"
, failed to "StartContainer" for "msj-treasure-map-nginx" with InvalidImageName: "Failed to apply default image tag \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06\": couldn't parse image reference \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06\": invalid reference format"
```

```bash
$ helm version                                                                                                                                                                             
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```

**Comment by BrendanBall** [comment]
I am also experiencing the same problem on helm 2.6.2.
```
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
```

**Comment by jayste** [comment]
+ 1

Stripping YAML down to JSON removes a lot of information, most type related. Means you can't type check values pre-deploy.

I guess this can be resolved by moving to a different yaml library. Maybe this one: https://github.com/go-yaml

**Comment by tarequeh** [comment]
While struggling with this issue today I found out that the `toString` filter can help with this:

`dockerPort: {{ .Values.dockerPort | toString }}`

Then I was able to pass the port in command line (`--set dockerPort=2376`) and have it interpreted correctly.

**Comment by cory-klein** [comment]
We just saw this on 2.7.2 and most of the workarounds don't really work for us except writing all the `--set` options to a local file and passing that via `helm -f locals.yml`.

**Comment by arschles** [comment]
I have also seen this in 2.7.2 (and filed #3246 as a result), so +1 on this issue. Like in https://github.com/kubernetes/helm/issues/3001, I was also using the git SHAs for my docker image tags. My workaround for now, FWIW, is to suffix image tags with `-gitsha`

**Comment by vpetersson** [comment]
+1 for me as well. 

```
$ helm version                                                                                                                                    ⏎
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

$ git rev-parse --short HEAD
6180689

$ helm upgrade foobar \
    -i charts/foobar \
    --set image.tag=$(git rev-parse --short HEAD) \
    --reuse-values
```
After deploy, I get this:

```
Failed to apply default image tag "gcr.io/foobar/foobar:6.180689e+06": couldn't parse image reference "gcr.io/foobar/foobar:6.180689e+06": invalid reference format
Error syncing pod
```

I also get `InvalidImageName` upon running `kubectl get pods`.

Appending `| toString` does not appear to make a difference for me. 

Using @ipedrazas trick (`\\"6180689\\"`) however does seem to do the trick.

**Comment by mparry** [comment]
We've also run into this bug a couple of times.

It seems to me that the change in #2467 was too broad. Certainly I would argue that this problem it has introduced is worse than the problem it solved.

**Comment by laverite** [comment]
can you just do: 

{{ .Values.tag | int64 }}

**Comment by bacongobbler** [comment]
@laverite in charts absolutely, but this is using the --set parser. This problem only exists for the --set parser. values passed in via values.yaml  are parsed correctly. :)

**Comment by jesselang** [comment]
It appears this is related to #3155

**Comment by arschles** [comment]
yep, believe so @jesselang

**Comment by arschles** [comment]
Also https://github.com/kubernetes/helm/issues/3246

**Comment by Xuhao** [comment]
Same problem here with helm 2.8.0.

**Comment by arturo-c** [comment]
@bacongobbler or @technosophos  I have a fix for this issue on #3599 , there's already one approval, just need another. Thanks!

**Comment by bacongobbler** [comment]
resolved via #3599

**Comment by OndraZizka** [comment]
Seeing this bug too with Helm 2.9.1

**Comment by OndraZizka** [comment]
I wonder why `helm lint` doesn't catch this? See #4099

**Comment by frankh** [comment]
I'm curious why this was solved by adding `--set-string`, instead of fixing what seems to me to be an obvious bug in `--set`.

Is it likely that anyone is intending numbers to get coerced to scientific notation in their yaml files?

**Comment by bacongobbler** [comment]
We can change how the [`--set` parser coerces integer values](https://github.com/kubernetes/helm/blob/1c2592975b21b78389c57aee07c9c6d962998d84/pkg/strvals/parser.go#L340-L345) in Helm 3, but generally speaking we've opted to prevent changing the expected behaviour of core functionality like `--set` since there are so many users running Helm in production. We can't also coerce all values in `--set` to strings since that'll break existing behaviour such as the expected behaviour around [null and truthy values](https://github.com/kubernetes/helm/blob/1c2592975b21b78389c57aee07c9c6d962998d84/pkg/strvals/parser.go#L328-L338) in values files, so `--set-string` was accepted as a workable solution for the time being.

**Comment by aliasmee** [comment]
@technosophos  thanks.
Example:
```bash
kind: Secret
data:
  some_db_port: {{ .Values.dbInfo.db_port | replace ":" "" | b64enc }}
```

it's work for me.

**Comment by bacongobbler** [comment]
@OndraZizka thank you for the (very passionate) feedback. We're definitely looking into addressing some of these wonky behavioral issues that the `--set` parser has for Helm 3, likely by replacing it with something similar to new `--set-string` parser.

I fully agree that the behavior of `--set` is *very* odd in this case (and even downright wrong), but we can't expect to replace an entire parsing library with another and be confident that there to be no other coercion bugs in the new system. Swapping coercion libraries would be considered a backwards-incompatible change.

For the time being, `--set-string` is a great feature and I highly recommend it to anyone else running into this bug to please use `--set-string` as much as possible when you don't rely on type coercion. That way, values are forced to be coerced as a string, and not as a float.

**Comment by jakubigla** [comment]
Unfortunately, when Ansible formats a dict to yaml (which is my values.yaml), it doesn't add any quotes, which is a big issue for me. I can't believe I have to use this bloody hack: `replace ":" ""`

**Comment by kesselborn** [comment]
if you need a work around that works without prefixing the tag with a `:` and removing it later, you can use this one (tl;dr: when tag is a number, use printf to print it, otherwise print the string you got)

```yaml
{{- $tag :=  .Values.image.tag }}
{{- $type := printf "%T" $tag }}
image: "{{ .Values.image.repository }}:{{if eq $type "float64"}}{{ printf "%.0f" $tag }}{{ else }}{{ $tag }}{{ end }}"
```

**Comment by itaied246** [comment]
The bug also happens with `helm ... -f myval.yaml`

**Comment by bacongobbler** [comment]
FYI, this was fixed in https://github.com/helm/helm/pull/6010.

**Comment by zackijack** [comment]
@bacongobbler still happening on me with helm version v2.14.3

**Comment by bacongobbler** [comment]
Can you open a new issue? Thanks.

**Comment by bacongobbler** [comment]
re-opening because of the need to revert #6010.

**Comment by sagarkal** [comment]
Any ETA when the fix would be available?

**Comment by bacongobbler** [comment]
see #6888.

**Comment by icanhazbroccoli** [comment]
@sagarkal to make sure we're on the same page: the aforementioned fix is only aiming to reach up Helm v3, not v2 (I'm declaring this as a random contributor, the actual decision is always up to the team). The change is relatively massive and shouldn't be considered 100% safe to get merged into 2.x branch, which is patch-only now. In the meantime, if you have a chance, it would be great if you could test the PR branch against your use case and let us know if things work as expected. That would help a lot!

**Comment by m0rganic** [comment]
Using `--set-string image.tag=6599236` worked for me with a plain template like this

```
  ...
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
  ...
```

**Comment by Rathgore** [comment]
Running into this with a large integer value specified in the chart's values file. It is implicitly converted to a float with scientific notation. Just casting the value to an `int` fixed this, and seems much cleaner than some of the other workarounds I've seen:

```yaml
# values.yaml

tomcat:
  maxPostSize: 2097152
```

```
# Cast to int when used

{{ .Values.tomcat.maxPostSize | int }}
```

**Comment by technosophos** [comment]
That is good to know! That is definitely an easy workaround compared to many of the ones I have seen. Thanks!

**Comment by m0rganic** [comment]
@Rathgore Casting to an int is perfect when dealing with ints all of the time but in my case the input value needs to be treated as a string but comes in the form of digits (sometimes). For example the shortened 7 length github commit hash, sometimes it's a string and sometimes it's just a string of digits. In this case passing in the value with the `--set-string` option works every time.

**Comment by Rathgore** [comment]
@m0rganic I haven't tested this, but you could try using `toString` instead of `int` or explicitly setting the type using `!!str`. This isn't needed if you're just using `--set-string` but we need this behavior for values defined in the chart as well.

**Comment by liuming-dev** [comment]
> @m0rganic I haven't tested this, but you could try using `toString` instead of `int` or explicitly setting the type using `!!str`. This isn't needed if you're just using `--set-string` but we need this behavior for values defined in the chart as well.

`toString` doesn't work, and in some cases, I couldn't use `!!str`.

**Comment by edobry** [comment]
Is there a plan to fix this behavior? This issue has been open for quite a while...

**Comment by technosophos** [comment]
See #6888. Otherwise, no. We've documented many patterns to use. But we haven't found a solution that solves more issues than it causes. Feel free to try your hand at a PR.

**Comment by edobry** [comment]
Thanks for the quick response! I'm not certain that any of the proposed workarounds solve my usecase but I'll try again.

**Comment by jesher** [comment]
> Does it work differently if you do `--set tag=\"1\"`?

in my case I used `""` in the int, float and bool values and it worked, thanks

**Comment by bacongobbler** [comment]
Based on [this comment](https://github.com/helm/helm/pull/6888#issuecomment-627178587), it may appear this is no longer an issue for Helm 3, just for Helm 2. I'd love to hear who is still running into this issue, how, and with what versions of Helm.

For Helm 2 users, we are only accepting security patches at this point, so we will not be looking to fix this bug for Helm 2. However, if this is still relevant for Helm 3, I'd appreciate more information from the community on this particular bug.

**Comment by ThaSami** [comment]
for helm 2 you may cast to whatever you want between the ( ) as the example below

{{- range $i := until (int .Values.deployment.numberofracks) }}
  - name: rack{{$i}}
{{- end}}

**Comment by bacongobbler** [comment]
I'm going to assume this has been fixed for Helm 3, as it's been 3 weeks since I last posted that this appears to have been fixed. If there are still others experiencing this issue with Helm 3, please feel free to discuss this and we can re-open this issue. Thanks!

**Comment by edobry** [comment]
This is still an issue; I'm on `3.3.0` and still experiencing this.

**Comment by bacongobbler** [comment]
Can you please provide a demonstration?

**Comment by edobry** [comment]
Happy to, but I'm not fully sure how to do that; I have a Chart which has in its `values.yaml` a field which looks like this:
```yaml
customEnv:
  SOME_ENV_VAR: 10000000
```
and then in `templates/deployment.yaml`, I have this:
```yaml
    ...
    containers:
      - name: someContainer
        env:
           {{- range $key, $value := .Values.customEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
    ...
```
When I run `helm template`, I get this value in the rendered output:
```yaml
    ...
    containers:
      - name: someContainer
        env:
            - name: "SOME_ENV"
              value: "1e+07"
   ...
```
and then my deployed application fails when it tries to parse the value of `SOME_ENV` as a number.

**Comment by bacongobbler** [comment]
Okay. I managed to reproduce the same issue following your instructions with Helm 3.3.1. Thank you. Re-opening.

**Comment by RytisLT** [comment]
I'm hitting the same issue for a slightly different angle. My `appVersion` is `8482e77`, if I reference `appVersion` anywhere it gets rendered as `+Inf`. This is fun to debug BTW.

**Comment by bacongobbler** [comment]
That’s to be expected. Unquoted, YAML parses that value as scientific notation (as `8482e77` means “8482 * 10^77”). If you want a value to be treated as a string, wrap it in quotes.

**Comment by felippe-mendonca** [comment]
I had this issue with contianer image tag. The problem were addressed creating the helper below:
```
+{{/* Generate Image Name */}}
+{{- define "helpers.image" }}
+{{- $tag := printf "%f" .Values.app.image.tag -}} 
+{{- if regexMatch "^[0-9]+\\.[0-9]+$" $tag }}
+{{ .Values.image.repository }}:{{ .Values.image.tag | int }}
+{{- else }}
+{{ .Values.image.repository }}:{{ .Values.image.tag }}
+{{- end }}
+{{- end }}
```
And then, at Deployment manifest:
```
   containers:
       - name: {{ template "helpers.fullname" . }}
         image: {{ template "helpers.image" . }}
```

**Comment by rajibmitra** [comment]
is this issue fixed ?

**Comment by bacongobbler** [comment]
No. See above.

**Comment by unixfox** [comment]
bump, still an issue

**Comment by urakagi** [comment]
I am using this workaround when I meet this problem on maybe-numeric commit ids:

```
{{- define "git.safeCommitID" -}}
{{- if .Values.git.commitID | toString | contains "e+" -}}
{{ .Values.git.commitID | toString | replace "." "" | regexFind "^\\d+" }}
{{- else -}}
{{ .Values.git.commitID }}
{{- end -}}
{{- end -}}
```

It solves problems if your original string never contains dot and `e+`, though I don't know if it's a very long number string anything will be omitted.

**Comment by jochenhebbrecht** [comment]
@urakagi unfortunately, that doesn't work if your value is: `1800000`

**Comment by harrysingh** [comment]
Is there a fix planned for this issue?

**Comment by Adhira-Deogade** [comment]
Any updates?

**Comment by darkn3rd** [comment]
This reproduces in helm v3.4.2

```
  {{- if $hasS3Keys }}
  s3_access_key: {{ .Values.backups.keys.s3.access | b64enc | quote }}
  s3_secret_key: {{ .Values.backups.keys.s3.secret | b64enc | quote }}
  {{- end }}
```

This results in:

```
helm.go:81: [debug] template: dgraph/templates/backups/secrets.yaml:22:61: executing "dgraph/templates/backups/secrets.yaml" at <b64enc>: invalid value; expected string
```

**Comment by ramanNarasimhan77** [comment]
I wrote a helper func and used the %v notation to workaround this


```{{- printf "%v" .Values.port -}}```

From the documentation https://helm.sh/docs/chart_template_guide/function_list/#printf 

```
%v the value in a default format
when printing dicts, the plus flag (%+v) adds field names
```

**Comment by radekkut** [comment]
I'm having the same problem when iterating through a range of integers:
```
    {{- range untilStep .Values.udpPortMin .Values.udpPortMax 1 }}
    - port: {{ . }}
      protocol: UDP
    {{- end }}
```
I'm defining these in values.yaml:
```
udpPortMin: 6000
udpPortMax: 6101
```
And I get an error while templating:
```
Error: template: chart-name/templates/service.yaml:11:31: executing "chart-name/templates/service.yaml" at <.Values.udpPortMin>: wrong type for value; expected int; got float64
```

**Comment by rootdeep** [comment]
> Another workaround we have used is to do stuff like this:
> 
> ```
> --set port=":1234567"
> ```
> 
> Then in the template:
> 
> ```
> {{ .Values.port | replace ":" "" }}
> ```

not elegant

**Comment by rootdeep** [comment]
> I'm hitting the same issue for a slightly different angle. My `appVersion` is `8482e77`, if I reference `appVersion` anywhere it gets rendered as `+Inf`. This is fun to debug BTW.
> 
> Edit:
> changing appVersion from `appVersion: 8482e77` to `appVersion: "8482e77"` fixed my issue

works also for me,   helm version 3.5.2

**Comment by Ailsa-Wu** [comment]
I have this issue in `Chart.yaml`.  Numeric abbrev commit hash `97665e46` will be converted to `+inf` after I run `helm package` or `helm chart save`.

My helm version:
```text
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
``` 

Before package: 

```yaml
annotations:
  ede.io/abbrevCommitHash: 97665e46
  ede.io/author: tony
  ede.io/commitMessage: |
    merge dev
  ede.io/committerDate: "2021-08-18T17:20:14+08:00"
apiVersion: v1
appVersion: 1.0.0
description: Some services.
name: my-service
version: 0.0.1-test
```

After package(and then export):
```yaml
annotations:
  ede.io/abbrevCommitHash: +Inf
  ede.io/commitMessage: |
    merge dev
  ede.io/committer: tony
  ede.io/committerDate: "2021-08-18T17:20:14+08:00"
apiVersion: v1
appVersion: 1.0.0
description: Some services.
name: my-service
version: 0.0.1-test
```

**Comment by yardenshoham** [comment]
bump, still an issue

**Comment by bencat-sixense** [comment]
I was able to fix it much easily than previous answers:

Bad parse:
`MY_INT: 3204063`
Result:
`value: "3.204053e+06"`

Good parse:
`MY_INT: "\"3204063\""`
Result:
`value: "3204063"`

**Comment by lexfrei** [comment]
bump

**Comment by joejulian** [comment]
Testing this with:
```
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

I performed this test:
```
helm create foo
cd foo
cat << EOF > templates/foo.yaml
value: {{ .Values.foo }}
type: {{ typeOf .Values.foo }}
EOF

helm template foo . --set foo=20161216 --show-only templates/foo.yaml
```
which results in
```
---
# Source: foo/templates/foo.yaml
value: 20161216
type: int64
```

I also tested 
```
 helm template foo . --set foo=201612e16 --show-only templates/foo.yaml
 ```

 ```
---
# Source: foo/templates/foo.yaml
value: 201612e16
type: string
```

Since this reflects the desired outcome of this issue, I'm closing it.

**Comment by momocow** [comment]
@joejulian Hi, your example works like a charm, but I found that it's still an issue if the tag is coming from `--reuse-values`.

**Comment by momocow** [comment]
I use `--set-string tag=1234567` to override the one in the legacy values (used by `--reuse-values`) and the tag no longer be `float64` but `string`.

It has been resolved! 🎉

**Comment by robcxyz** [comment]
Is this issue really closed or is the helm team satisfied with not supporting large integers.  I think we'd all be happy to put in a `| quote` in the template if it worked like it did in the old versions but now it seems to not. 

Not going to lie, as the official package manager of kubernetes, this should be supported after 5 years.

**Comment by joejulian** [comment]
@robcxyz I tested the subject of this issue with the latest version and it passed. I'm not sure what https://github.com/helm/helm/issues/1707#issuecomment-1099952879 is referring to. Is the issue germane to this issue's subject, or is it a different issue? Do you have a repro?

Happy to reopen if this isn't actually satisfied but like you say, this issue hasn't been addressed since 2016. I fear that if the original description is satisfied, reopening it for a condition that's at the bottom of the comments still won't gain any attention. Perhaps a new issue for your specific concern with a repro might be more effective at getting maintainer attention?

**Comment by schnerring** [comment]
@joejulian I tried your example and have mixed results.

````text
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Running `helm template foo . --set foo=20161216 --show-only templates/foo.yaml`:

```text
---
# Source: foo/templates/foo.yaml
value: 20161216
type: int64
```

Running `helm template foo . --show-only templates/foo.yaml`:

```text
---
# Source: foo/templates/foo.yaml
value: 2.0161216e+07
type: float64
```

Interestingly multiplying by 1 fixes the issue:

```text
value: {{ mul .Values.foo 1 }}
```

**Comment by thatsnotamuffin** [comment]
@joejulian I'm having this issue right now with `v3.11.2` using a value of `93572e3` during the `helm template` command I'm getting this as the image tag `9.3572e+07`.

I'm not seeing how its resolved or a workaround using `helm install` or `helm upgrade`. I'd rather avoid a hacky workaround if I can.

**Comment by Mo0rBy** [comment]
I'm having this exact same issue using `v3.12.2`.

My `values.yaml` file contains : `servicePort: 1433` and I am attempting to create a database url using the `printf` function, something like this:
`{{ printf "jdbc:sqlserver://%s:%d" .Values.myString .Values.servicePort }}`

I get the following result: `jdbc:sqlserver://psdt-mssql:%!d(float64=1433)`

Happy to create a new issue for this as this is an old thread, but if I do, can it actually be fixed??

**Comment by jhonsanchez** [comment]
> {{ printf "jdbc:sqlserver://%s:%d" .Values.myString .Values.servicePort }}

you could try this:
`{{ printf "jdbc:sqlserver://%s:%s" .Values.myString (.Values.servicePort | toString) }}`

**Comment by myron0815** [comment]
Is this something we should reopen / create a new issue?  

Helm 3.11/3.12/3.13 all render here numbers >= 1.000.000 as exponent, and all values are float64  
Is there any use-case for this i'm failing to see?

Treating all numbers as String could not have been the intention of the creators :)  
Any multiplying by one, well, yes, it does work, but... yuck.

**Comment by sarasensible** [comment]
Vote for reopening - just hit this too.

**Comment by ivankatliarchuk** [comment]
Simple test

input 
```yml
test1: v11724e28
test2: 11724e28
test3: 2.10.6
test4: v2.10.6
```

helm template
```
test1: {{ .Values.test1 }}
test1Type: {{ typeOf .Values.test1 }}
test2: {{ .Values.test2 }}
test2Type: {{ typeOf .Values.test2 }}
test3: {{ .Values.test3 }}
test3Type: {{ typeOf .Values.test3 }}
test4: {{ .Values.test4 }}
test4Type: {{ typeOf .Values.test4 }}
```

output for a helm template command
```yml
---
# Source: test-helm/templates/test.yaml
test1: v11724e28
test1Type: string
test2: 1.1724e+32
test2Type: float64
test3: 2.10.6
test3Type: string
test4: v2.10.6
test4Type: string
```

Can we have it fixed at some point?

**Comment by nikicat** [comment]
@ivankatliarchuk Isn't it an expected behavior? Yaml parser sees 11724e28 as a float.

**Comment by Mo0rBy** [comment]
> @ivankatliarchuk Isn't it an expected behavior? Yaml parser sees 11724e28 as a float.

This is exactly what this thread is about no? Why does `11724e28` get parsed as a float when the other cases are all string. I believe the reason it is being parsed as a float is because it is reading it as scientific number notation (`e28` means `x10^28` (multiply by 10 to the power of 28)), but I really hate that it's not consistent, and I don't think many users (if any) need to parse things in scientific number notation when using yaml.

**Comment by Mo0rBy** [comment]
Also, within my own specific issue, I was using `%d` to indiciate that I have a number value, I want to put that into the string format, but it would print as `%!d(float64=1433)` rather than putting `1433` into that position.

**Comment by nikicat** [comment]
> This is exactly what this thread is about no?

I suppose this thread is about the command line argument parser, not the YAML parser.

**Comment by dberardo-com** [comment]
after reading through all this discussion i am stil confused ... is there any workaround so far ? like using "| quote" ? or what ?

**Comment by sebastianpiskorski** [comment]
> after reading through all this discussion i am stil confused ... is there any workaround so far ? like using "| quote" ? or what ?
`| quote` doesn't work

**Comment by MalteMagnussen** [comment]
Vote for reopening. Just saw this as well.

`deployment.yaml`:

```
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```

with `values.yaml`:

```yaml
image:
  tag: 87940363
```

becomes desired manifest of:

```
        - image: 'redacted-image-name:8.7940363e+07'
```

**Comment by aoledk** [comment]
> Vote for reopening. Just saw this as well.
> 
> `deployment.yaml`:
> 
> ```
>           image: "{{ .Values.sidecar.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
> ```
> 
> with `values.yaml`:
> 
> ```yaml
> image:
>   tag: 87940363
> ```
> 
> becomes desired manifest of:
> 
> ```
>         - image: 'redacted-image-name:8.7940363e+07'
> ```
> 
> Using this does not work, because as soon as the tag changes to something that isn't an int, we have a helm problem.
> 
> ```
>           image: "{{ .Values.sidecar.image.repository }}:{{ .Values.image.tag | int }}"
> ```

You can quote image.tag with `""` to resolve this problem.

> https://helm.sh/docs/chart_template_guide/yaml_techniques/#scalar-types-in-yaml

**Comment by rehevkor5** [comment]
The workaround appears to be to use `--set-string` instead of `--set`, added by https://github.com/helm/helm/pull/3599

**Comment by bcdurden** [comment]
How is this still a problem over 7 years later?

**Comment by shivanshs9** [comment]
Sorry to necro this thread, but here's a small Helm function to handle the edge-cases:
```
{{/*
Because of Helm bug (https://github.com/helm/helm/issues/3001), Helm converts
int value to float64 implictly, like 2748336 becomes 2.748336e+06.
This breaks the output even when using quote to render.

Use this function when you want to get the string value only.
It handles the case when the value is string itself as well.
Parameters: is string/number
*/}}
{{- define "stringOrNumber" -}}
{{- if kindIs "string" . }}
  {{- print . -}}
{{- else  }}
  {{- int64 . | toString -}}
{{- end -}}
{{- end -}}

```

Simply use it in your template yamls like so:
```
app.kubernetes.io/version: {{ include "stringOrNumber" .Values.global.version | quote }}
```
^ handles both these cases:
global.version = 2748336
global.version = "2748336"
