### ISSUE TITLE
Regression on Helm 3.18.6 during JSON schema validation of values.yaml

### ISSUE THREAD

**Issue by DarioAxual** [helm/helm#31177]
### What happened?

I'm installing an helm chart within a GO application that uses the helm library with the `action` package.

When performing an Install object or Upgrade object to install the chart, I'm getting the following errors:

```
{
    "time": "2025-08-21T12:23:09.440868636Z",
    "level": "ERROR",
    "msg": "Failed to install via helm",
    "error": "values don't meet the specifications of the schema(s) in the following chart(s):\nksml:\n- at '/ksmlRunnerConfig/kafka': invalid jsonType map[string]string\n- at '/podLabels': invalid jsonType map[string]string\n"
}
```

### What did you expect to happen?

The chart is installed successfully 

### How can we reproduce it (as minimally and precisely as possible)?

Create a GO application that has the following types and function.

Helm Service
```
type helmService struct {
	actionConfig *action.Configuration
	chart        *chart.Chart
}
```

HelmDeployRequest
```
type HelmDeployRequest struct {
	Namespace   string
	Values      map[string]interface{}
	Tenant      string
	Instance    string
	Environment string
	Application string
}
```

DeployKSMLHelm

```
func (h *helmService) DeployKSMLHelm(ctx context.Context, req HelmDeployRequest) (*release.Release, error) {
	releaseName := generateReleaseName(req.Tenant, req.Instance, req.Environment, req.Application)

	isUpgrade, err := isUpgradeOrInstall(ctx, h.actionConfig, releaseName)
	if err != nil {
		slog.ErrorContext(ctx, "Failed to deploy", slog.Any("error", err))
		return nil, err
	}

	if isUpgrade {
		// run helm upgrade
		upgradeClient := action.NewUpgrade(h.actionConfig)
		upgradeClient.Namespace = req.Namespace
		rel, err := upgradeClient.RunWithContext(ctx, releaseName, h.chart, req.Values)
		if err != nil {
			slog.ErrorContext(ctx, "Failed to upgrade via helm", slog.Any("error", err))
			return nil, err
		}
		return rel, err

	} else {
		// run helm install
		installClient := action.NewInstall(h.actionConfig)
		installClient.ReleaseName = releaseName
		installClient.Namespace = req.Namespace
		rel, err := installClient.RunWithContext(ctx, h.chart, req.Values)
		if err != nil {
			slog.ErrorContext(ctx, "Failed to install via helm", slog.Any("error", err))
			return nil, err
		}
		return rel, nil
	}
}
```

values.yaml

```
{
    "deploymentMode": "statefulset",
    "ksmlDefinitions": {
        "ksml-definition.yaml": "{streams: {sensor_source_avro: {topic: ksml_sensordata_avro, keyType: string, valueType: 'avro:SensorData'}}, functions: {log_message: {type: forEach, parameters: [{name: format, type: string}], code: 'log.info(\"Consumed {} message - key={}, value={}\", format, key, value)'}}, pipelines: {consume_avro: {from: sensor_source_avro, forEach: {code: 'log_message(key, value, format=\"AVRO\")'}}}}"
    },
    "ksmlRunnerConfig": {
        "definitions": {
            "ksml": "ksml-definition.yaml"
        },
        "kafka": {
            "application.id": "io.demo.sensor-inspector",
            "bootstrap.servers": "broker:9093",
            "environment": "dev",
            "instance": "sandbox",
            "schema.registry.url": "http://schemaregistry:8081",
            "tenant": "demo"
        }
    },
    "podLabels": {
        "axual.io/application": "sensor-inspector",
        "axual.io/environment": "dev",
        "axual.io/instance": "sandbox",
        "axual.io/tenant": "demo"
    },
    "replicaCount": 1,
    "resources": {
        "limits": {
            "cpu": "800m",
            "memory": "900Mi"
        },
        "requests": {
            "cpu": "400m",
            "memory": "600Mi"
        }
    },
    "schemaDefinitions": {},
    "securityContext": {
        "allowPrivilegeEscalation": false,
        "capabilities": {
            "drop": [
                "all"
            ]
        }
    }
}
```

the Helm Chart is https://github.com/Axual/ksml/tree/main/packaging/helm-charts/ksml

the values.schema.json is https://github.com/Axual/ksml/blob/main/packaging/helm-charts/ksml/values.schema.json

### Helm version

3.18.6

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.30.5
WARNING: version difference between client (1.32) and server (1.30) exceeds the supported minor version skew of +/-1
```

</details>

**Comment by TerryHowe** [comment]
Did you look at the other 3.18.6 schema and rendering issues?

**Comment by DarioAxual** [comment]
Yes, I think they are related but not actually sure they are the same issue and wanted to report my own issue to let people correlate with already opened issues.

Maybe this https://github.com/helm/helm/issues/31148 is the same issue I'm having but not sure.

**Comment by mvillafuertem** [comment]
We’ve noticed that with Helm version 3.18.6, we’re seeing this type of error with the Istio charts.

```
==> Linting /tmp/helmfile3232538154/istio-system/istio-gateway/istio-release/gateway/1.22.4/gateway
[ERROR] values.yaml: - at '': additional properties 'podDisruptionBudget', 'volumes', 'service', 'volumeMounts', 'defaults', 'autoscaling' not allowed

[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
```

https://github.com/istio/istio/pull/57457

**Comment by benoittgt** [comment]
@mvillafuertem but it is now fixed (in the new release) ?

**Comment by mvillafuertem** [comment]
@benoittgt I see that the latest Istio release is 1.27.0. Is that the one you mean?

**Comment by benoittgt** [comment]
It has not been release yet propbably. I did another PR to fix the build too. https://github.com/istio/istio/pull/57507

**Comment by benoittgt** [comment]
@mvillafuertem They are many [new versions](https://github.com/istio/istio/releases) released. You should try.

**Comment by AndreiBarbuOz** [comment]
@benoittgt , the issue is still present in `3.19.0` release

**Comment by marcoandredinis** [comment]
> I'm installing an helm chart within a GO application that uses the helm library with the `action` package.

Is `podLabels` in your go code a `map[string]string`?
If so, try changing it to `map[string]any`.

I faced a similar issue, and fixed it by changing the go type used.
The jsonschema type is `Object` which _translates_ to `map[string]any`.

The package used to do validations in `helm` changed, and this one is more strict.

**Comment by benoittgt** [comment]
@AndreiBarbuOz do you have steps to reproduce the error?  
I’ve fixed multiple charts, and it was always an issue with how the `values.schema.json` or the values were defined.

**Comment by jlcrow** [comment]
Having issues with 3.19, assuming this is still a problem - getting errors installing OpenTelemetry's Operator chart. I've rolled helm back to 3.18.3

**Comment by benoittgt** [comment]
@jlcrow do you have a command to help me reproducing the issue? I see no issue when running.
```sh
helm install opentelemetry-operator open-telemetry/opentelemetry-operator \
--set "manager.collectorImage.repository=ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s" \
--set admissionWebhooks.certManager.enabled=false \
--set admissionWebhooks.autoGenerateCert.enabled=true
```

With v3.19

**Comment by alxlassian** [comment]
We have similar issue with 3.19 

```
- at '/microservice': 'allOf' failed
  - at '/microservice/ingress': false schema
```
and everything works with 3.18.3

**Comment by jlcrow** [comment]
> [@jlcrow](https://github.com/jlcrow) do you have a command to help me reproducing the issue? I see no issue when running.
> 
> helm install opentelemetry-operator open-telemetry/opentelemetry-operator \
> --set "manager.collectorImage.repository=ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s" \
> --set admissionWebhooks.certManager.enabled=false \
> --set admissionWebhooks.autoGenerateCert.enabled=true
> With v3.19

I was installing an older version of the chart - 0.84.2 - the error I received:

helm upgrade --install opentelemetry-operator open-telemetry/opentelemetry-operator --atomic --timeout 1800s --version 0.84.2 --create-namespace -n otel-operator
```
Release "opentelemetry-operator" does not exist. Installing it now.
Error: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
"file:///values.schema.json#" is not valid against metaschema: jsonschema validation failed with 'https://json-schema.org/draft/2019-09/schema#'
- at '': 'allOf' failed
  - at '/properties/manager': 'allOf' failed
    - at '/properties/manager/properties/featureGates': 'allOf' failed
      - at '/properties/manager/properties/featureGates/examples': got string, want array
```

**Comment by benoittgt** [comment]
@jlcrow It seems that, for now, the only available option is to either upgrade to the latest chart — which includes the correct schema ([ref](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1805#issuecomment-3192700891)) — or, in the meantime, stick to an older Helm version.  
I’d recommend migrating to a more recent chart version when possible.

@alxlassian As [mentioned before](https://github.com/helm/helm/issues/31177#issuecomment-3309657264), if this is your chart, please check the schema definition to address any validation issues.  
If it’s a public chart, could you share a link?  
At the moment, I haven’t found any issue on the Helm side.

**Comment by benoittgt** [comment]
For additional context:  

Helm [v3.18.5](https://github.com/helm/helm/releases/tag/v3.18.5) switched its JSON schema library from [github.com/xeipuuv/gojsonschema](https://github.com/xeipuuv/gojsonschema) to [github.com/santhosh-tekuri/jsonschema/v6](https://github.com/santhosh-tekuri/jsonschema/v6), likely for [security reasons](https://github.com/helm/helm/security/advisories/GHSA-9h84-qmv7-982p).  

The new library is **stricter in validation** of `values.schema.json` and follows the JSON Schema [draft-7 specification](https://json-schema.org/draft-07/draft-handrews-json-schema-01).  
That’s why issues that were previously ignored silently may now surface as explicit validation errors.  

**Recommendation:**  
Fix the `values.schema.json` or adjust the chart values based on the reported validation errors.  
You can refer to similar fixes made in the Istio chart:  
- Schema fix: [istio/istio#57457 (values.schema.json)](https://github.com/istio/istio/pull/57457/files#diff-34dcfa12b81edd5223fea8e91a8f7442d3c674a6252b9edd62ae8e0551eb26c4)  
- Detailed explanation: [istio/istio#57457](https://github.com/istio/istio/pull/57457)

I think the issue can be closed.

**Comment by scottrigby** [comment]
Answered in https://github.com/helm/helm/issues/31177#issuecomment-3378769348 and https://github.com/helm/helm/issues/31177#issuecomment-3380147813.
