### ISSUE TITLE
Alias ignored in dependend subchart

### ISSUE THREAD

**Issue by floyd871** [helm/helm#31187]
### What happened?

I have a helmchart (top-level) which imports a subchart (second-level) twice. Same version with a different alias.
This subchart (second-level) has also a subchart (third-level), which could be disabled via condition.
Per default in the values of second-level disables the thrid-level-chart.

Now, when you render the top-level-chart the third-level-chart is rendered.

This does not happen when you import the second-level-chart only once.

### What did you expect to happen?

Third-level-chart is NOT rendered and ignored

### How can we reproduce it (as minimally and precisely as possible)?

[chart-bug.zip](https://github.com/user-attachments/files/21983154/chart-bug.zip)

CD to top-level and do a:

```
❯ helm template .
---
# Source: top-level/charts/second-level-1/charts/third-level/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: release-name
  chart: third-level
  labels:
    name: release-name
```

### Helm version

<details>

```console
$ helm version
version.BuildInfo{Version:"v3.18.6", GitCommit:"b76a950f6835474e0906b96c9ec68a2eff3a6430", GitTreeState:"clean", GoVersion:"go1.24.6"}
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.4
Kustomize Version: v5.6.0
Server Version: v1.32.3
```

</details>

**Comment by tanktobbit** [comment]
Bug is resolved in helm 4.0.0.

<img width="1307" height="283" alt="Image" src="https://github.com/user-attachments/assets/7159a538-f52c-4eb0-800b-ce27304c0dd4" />

**Comment by Antoinep77** [comment]
Hello, I added a PR for a fix on helm 3 for this issue.

**Comment by YuleZ** [comment]
Still have this bug with 4.1.1 - reproducable with https://github.com/YuleZ/helm-alias-issue

**Comment by frittentheke** [comment]
@Antoinep77 @YuleZ so the bug still exists?

**Comment by YuleZ** [comment]
I checked again with https://github.com/YuleZ/helm-alias-issue and it's still reproducable. 
I'll check linting on #31847 so this can be resolved.
