### ISSUE TITLE
Proposal: helm template should also order resources in "useful creation order"

### ISSUE THREAD

**Issue by danderson** [helm/helm#3554]
In https://github.com/kubernetes/helm/pull/1238 , Tiller was changed to order resources before sending to k8s, so that e.g. namespaces are created before objects in that namespace.

It would be nice if `helm template` also did this useful ordering. I'm creating a Helm package for my software, but I also want to keep a "plain" manifest for people who just want to `kubectl apply`. I can do this by rendering the Helm templates, but it generates the output in a non-deterministic order, which might not be valid.

**Comment by jascott1** [comment]
Hi @danderson 

Are you running the helm template plugin? I ask because `helm template` is now in core and should have iirc "mostly" deterministic ordering just like Tiller. The mostly part is due to unknown types (types not explicitly in the list) being sorted alphabetically. If you are using `helm template` in core and seeing inconsistencies we should investigate because that sounds like a bug.

**Comment by igalarzab** [comment]
This is fixed probably with #5186

**Comment by tmshort** [comment]
Using Helm 3.0.2, this still appears to be a problem. I had an istio pre-install chart with 3 namespaces, a PriorityClass, a Role, a RoleBinding a ServiceAccount and a ClusterRoleBinding. Every execution of `helm template` would produce different results, with one case of the istio-system namespace coming last, causing other configuration to fail since it depended on namespace to be configured first.

**Comment by hickeyma** [comment]
@tmshort Fix for v3 is #7266 which will be in 3.0.3 release.
