### ISSUE TITLE
Nested `null` values don't remove keys as expected

### ISSUE THREAD

**Issue by aeijdenberg** [helm/helm#5184]
<https://github.com/helm/helm/pull/2648> allows for deletion of keys by setting `null` values in a `values.yaml` file. However it doesn't work for nested values, e.g.:

```yaml
web:
  livenessProbe:
    httpGet: null
    exec:
      command:
      - curl
      - -f
      - http://localhost:8080/api/v1/info
```

Will not remove `web.livenessProbe.httpGet` from the original values, rather it just overrides the value with `null` and prints the warning:

```
2019/01/18 11:30:07 Warning: Merging destination map for chart 'concourse'. Cannot overwrite table item 'httpGet', with non table value: map[path:/api/v1/info port:atc]
```

Ironically, above is a small variant on the example given in the docs, which I'm pretty sure does not actually do what it claims to: <https://docs.helm.sh/chart_template_guide/#deleting-a-default-key>

I suspect that since the template rendering doesn't seem to differentiate much between a null value and a value not being specified, that this warnings are being ignored and not having much effect.

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

EKS

**Comment by bacongobbler** [comment]
@scottrigby, do you by any chance want to take a gander at this one?

**Comment by bacongobbler** [comment]
Marking as question/support until it's been confirmed that this is indeed a bug according to the original author.

**Comment by cdenneen** [comment]
stable/filebeat

With `null` or `nil` I'm seeing the same thing... the key isn't removed... it's overwritten as `null/nil` but not removed and when you are replacing it with different key it causes problem:
```yaml
---values.yml in the Chart
output.file:
  path: /var/log/foo.log
```
```yaml
---my overrides
output.elasticsearch:
   hosts:
      - 'http://localhost:9200'
output.file: null
```
or
```yaml
---my overrides
output:
  elasticsearch:
     host:
      - 'http://localhost:9200'
  file: null
```
or
```yaml
---my overrides
output:
  elasticsearch:
     hosts:
      - 'http://localhost:9200'
output.file: null
```

```
» k get secret filebeat -o jsonpath="{.data.filebeat\.yml}" | base64 -D
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
      prospectors:
        path: ${path.config}/prospectors.d/*.yml
        reload.enabled: false
    filebeat.prospectors:
    - enabled: true
      fields:
        apenv: dev
        app: kubernetes
        log_category: kubernetes
      fields_under_root: true
      paths:
      - /var/log/*.log
      - /var/log/messages
      - /var/log/syslog
      type: log
    - containers.ids:
      - '*'
      fields:
        apenv: dev
        app: kubernetes
        log_category: kubernetes
      fields_under_root: true
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
      - drop_event:
          when:
            equals:
              kubernetes.container.name: filebeat
      type: docker
    http.enabled: true
    http.port: 5066
    output:
      elasticsearch:
        hosts:
        - http://localhost9200
    output.file: null
    processors:
    - add_cloud_metadata: null
```

pod errors as:

```
Exiting: error unpacking config data: more than one namespace configured accessing 'output' (source:'filebeat.yml')
```

**Comment by PosicubeBeege** [comment]
I'm also encountering this exact issue with the filebeat chart. 

@cdenneen You can get around file output specifically with `config.output.file.enabled=false`.

I'm encountering an issue where I want to use the new `inputs` key for filebeat but cannot remove the `prospectors` key.

Existing values:
```
config:
  filebeat.prospectors:
    - type: log
      enabled: true
      paths:
        - /var/log/*.log
        - /var/log/messages
        - /var/log/syslog
```

My override:  `--set config.filebeat.prospectors=null`

Result: (config is used to set a Secret value)
```
filebeat:
  prospectors: null
```

**Comment by pjanuario** [comment]
I also encountered this problem with `stable/kibana` and `stable/filebeat` the keys will default to the chart values even when `!!null` is specified.

**Comment by cdenneen** [comment]
@aeijdenberg believe your PR just requires labels updated to be reviewed

**Comment by scottrigby** [comment]
Hey @bacongobbler sorry I missed your question in https://github.com/helm/helm/issues/5184#issuecomment-456138448. I can verify it is a bug. In #2648 I really should have added a test that matched the documented example. I had meant to get back to this but #5185 looks promising! 👏 will respond over there

**Comment by wxdao** [comment]
Hi @scottrigby . May I know which release will include #5185's fix? I just encountered this problem when trying to remove resources definitions on istio chart.

**Comment by cc-stjm** [comment]
This is supposed to be in 2.14.2 - but I can't get it to work.

I'm following a very similar example to that at the top of the issue - the only difference I can see is that I'm trying to delete a value set in a subchart (in my case, logstash).

I have tried:
- setting logstash.livenessProbe.httpGet to `null`, `~` and `{}` in the main chart's values.yaml, or on the command line. In both cases, "helm template" shows that the original value is still there (i.e. I'm still getting httpGet set) - and this is consistent with what I see for "helm install" 
- setting logstash.livenessProbe.httpGet to "nil" - in this case the value does get overwritten, but to the string "nil" which isn't a valid value to use here, so kubernetes rejects the template.

Have I misunderstood and this didn't make it into 2.14.2 - or is there still an issue?

(Chart demonstrating this: [demo.zip](https://github.com/helm/helm/files/3435414/demo.zip))

**Comment by bacongobbler** [comment]
The patch was cherry-picked into 2.14.2 according to the release notes so it should be available.

**Comment by cc-stjm** [comment]
In which case, I'm not sure this bug is fixed - should it be re-opened or a new issue created? Can someone else have a look at the chart I attached to the above and see if they see different?

**Comment by aeijdenberg** [comment]
@cc-stjm @bacongobbler - I am able to reproduce the issue, and I think this test demonstrates it:

```golang
func TestSubchartCoaleseWithNullValue(t *testing.T) {
	v, err := CoalesceValues(&chart.Chart{
		Metadata: &chart.Metadata{Name: "demo"},
		Dependencies: []*chart.Chart{
			{
				Metadata: &chart.Metadata{Name: "logstash"},
				Values: &chart.Config{
					Raw: `livenessProbe: {httpGet: {path: "/", port: monitor}}`,
				},
			},
		},
		Values: &chart.Config{
			Raw: `logstash: {livenessProbe: {httpGet: null, exec: "/bin/true"}}`,
		},
	}, &chart.Config{})
	if err != nil {
		t.Errorf("Failed with %s", err)
	}
	result := v.AsMap()
	expected := map[string]interface{}{
		"logstash": map[string]interface{}{
			"global": map[string]interface{}{},
			"livenessProbe": map[string]interface{}{
				"exec": "/bin/true",
			},
		},
	}
	if !reflect.DeepEqual(result, expected) {
		t.Errorf("got %+v, expected %+v", result, expected)
	}
}
```

The problem, so far as I can tell, is that `CoalesceValues()` results in more than one call to the underlying function that coaleces the values:
https://github.com/helm/helm/blob/e04fa72f6f211cae68c362f9b7c62f06dc51493e/pkg/chartutil/values.go#L164-L180

ie line 173 above is called with the `httpGet` set to `null`, but the value it returns has deleted that key from the map (as intended). But then that output is passed a 2nd time as input to the 2nd set of coalescing (line 179), and then since key no longer exists, it defaults to the value in the chart.

Unfortunately I'm unlikely to have time available in the near future to go any further - I've changed roles and am not currently using Helm, and the answer on how to solve isn't obvious to me. Hopefully the above is helpful in resolving.

**Comment by sgillespie** [comment]
In fact, I just upgraded 2.14.0 => 2.14.2. Not only does the `null`ed key still exist, but it also contains the previous value. The previous behavior just made it null, so I believe this has actually regressed.

**Comment by bacongobbler** [comment]
@aeijdenberg can you please look into @sgillespie's inquiry? If there's a regression, then we need to back that PR out unless you can determine a fix.

**Comment by aeijdenberg** [comment]
@bacongobbler , while I haven't explictly tested 2.14.0, what @sgillespie matches the behaviour I referred to in <https://github.com/helm/helm/issues/5184#issuecomment-517059748>. Sadly I think it's a case of the unit tests passing, but the end to end failing - as the individual components are being used in series, which makes removing a key in an earlier stage makes it have no effect in later stages (and is why the original values are coming through).

I agree it's a regression, though backing it out is also a regression for anyone relying on the new behaviour.

I've had a quick go at a relatively minor patch which I think will reduce the impact (and fixes the test I added above) in #6146 - I'm sorry we got this wrong the in last attempt.

**Comment by bacongobbler** [comment]
This might've been fixed in https://github.com/helm/helm/pull/6080. That PR fixes the case where coalesceDeps is called twice. Can someone confirm with master?

**Comment by sgillespie** [comment]
This does indeed seem to fix the issue. A quick naive test:

Subchart values:
```
prop:
  nested:
    val: true
```

Parent chart values:
```
sub:
  prop:
    nested: null
```

Output as expected is `{}`

**Comment by arnaud-deprez** [comment]
Hi,

I'm using helm `2.15.0` and I've still met this issue.

Given a subchart with values:

```yaml
securityContext:
  runAsUser: 65534
  fsGroup: 65534
```

Where the values are used with `toYaml`

And in a parent chart values:

```yaml
sub:
  securityContext:
  runAsUser: null
```

Then the actual output is:

```yaml
securityContext:
  runAsUser: 65534
  fsGroup: 65534
```

While it should have been:

```yaml
securityContext:
  fsGroup: 65534
```

**Comment by creinig** [comment]
Not trying to rain on your parade, but I'm still seeing this with helm v3.0.1

version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

When trying to install stable/ignite I have to unset a value, but helm appears to just set the value to null/nil, causing k8s to balk in the validation step.

To reproduce, save this as `bug5184-ignite.yaml` (to override values from the chart's defaults: https://github.com/helm/charts/blob/master/stable/ignite/values.yaml):

```
persistence:
  enabled: true   # <-- without this, the keys in question are ignored
  persistenceVolume:
    provisionerParameters:
      type: null  # <-- I want to unset this key
  walVolume:
    provisionerParameters:
      type: null  # <-- I want to unset this key
```

Then use it as values file for an ignite install:

```
helm install runtimedb stable/ignite --version 1.0.1 --values bug5184-ignite.yaml --debug --dry-run | less
```

The result I'm getting is this error message, showing that the value I wanted to unset has been set to `nil`:

```
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: /home/creinig/.cache/helm/repository/ignite-1.0.1.tgz

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in StorageClass.parameters.type
helm.go:76: [debug] error validating "": error validating data: unknown object type "nil" in StorageClass.parameters.type
helm.sh/helm/v3/pkg/kube.scrubValidationError
        /home/circleci/helm.sh/helm/pkg/kube/client.go:520
helm.sh/helm/v3/pkg/kube.(*Client).Build
        /home/circleci/helm.sh/helm/pkg/kube/client.go:135
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:229
[...]
```

What I've also tried:

* Setting the value to something different / not overriding it at all
  * => The PersistentVolumeClaim is stuck in "Pending" because there's an extra "type" option that's not supported by the provider
  * => it's definitely that value causing the problems
* Setting the value(s) to `null` via `--set`
  * Same behavior as when setting it in the file

When only setting a single value to `null` via the command line, while at the same keeping ignite persistence disabled (so that the storageclass template is not generated and the parameter in question is ignored)...
```
helm install myignite stable/ignite --version 1.0.1 --set persistence.persistenceVolume.provisionerParameters.type=null --debug --dry-run | less
```
... there is proper debug output instead of an error, but it shows that the value is just set to `null` (comments added by me):

```
NAME: myignite
LAST DEPLOYED: Tue Dec 10 09:43:40 2019
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
persistence:
  persistenceVolume:
    provisionerParameters:
      type: null   # <-- Set via the command line

COMPUTED VALUES:
affinity: {}
dataStorage:
  config: ""
env:
  IGNITE_QUIET: "false"
  JVM_OPTS: -Djava.net.preferIPv4Stack=true
  OPTION_LIBS: ignite-kubernetes,ignite-rest-http
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: apacheignite/ignite
  tag: 2.7.6
nameOverride: ""
nodeSelector: {}
peerClassLoadingEnabled: false
persistence:
  enabled: false
  persistenceVolume:
    provisioner: kubernetes.io/aws-ebs
    provisionerParameters:
      fsType: ext4
      type: null  # <-- Set to null instead of removed
    size: 8Gi
  walVolume:
    provisioner: kubernetes.io/aws-ebs
    provisionerParameters:
      fsType: ext4
      type: gp2  # <-- This is what the default looks like
    size: 8Gi
rbac:
  create: true
replicaCount: 2
resources: {}
serviceAccount:
  create: true
  name: null
tolerations: []
```

**Comment by mvisonneau** [comment]
I have ran into the exact same issue using `3.0.1`, it might be good to reopen this issue ?

**Comment by sstarcher** [comment]
After moving from helm v2.16.1 to v3.0.2.  I have had this issue with annoations unsetting and cpu limits.

**Comment by tatchiuleung** [comment]
I just encounter this issue in `2.14.1` and `3.0.2`. Any update on this?

**Comment by tuzla0autopilot4** [comment]
In cases where I know the helm chart is simply using and true/false if test, I override the value with a non-table value like 0. I get a lot of warnings like `Overwriting table item 'x', with non table value: 0`, but I at least get a workaround in cases where I don't want a stanza included. My preference would be for null to work, but this is an ugly workaround.

**Comment by irothschild** [comment]
I have set values to null (and left them null in my values files) and ignore the long list of table warnings which is OK for now but I'd really just like to do a one-time cleanup of the old incorrect values stored in kubernetes. Until this value deletion bug is fixed, is there a manual way to edit the values on an existing deployment with no downtime?

**Comment by kiran-golang** [comment]
Running into the same issue with `liveness` and `readiness` probes.
[Deleting Default Key](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key) from the template guide does not work.

**Comment by bacongobbler** [comment]
Please give #7743 a try. It looks like the commits made to Helm 2 were not ported over to Helm 3, which is why many users would be seeing this behaviour on the newer release.

**Comment by vbuciuc** [comment]
Still seeing this problem with helm 2.16.3 but only when there's a requirements.yaml listing the  subchart as dependency.

boo is the subchart and foo is the parent chart:
`
vibu@item-ax35755:~/work$ cat boo/values.yaml 
object:
  fromSubchart:
    hello: from boo
vibu@item-ax35755:~/work$ cat foo/values.yaml 
boo:
  object:
    fromParent:
      hello: from foo
    fromSubchart: null
vibu@item-ax35755:~/work$ cat boo/templates/test.yaml 
{{ toYaml .Values.object }}
vibu@item-ax35755:~/work$ cat foo/requirements.yaml 
dependencies:
- name: boo
  repository: file://../boo
  version: 0.1.0
  
    

`



`vibu@item-ax35755:~/work/foo$ helm version -c
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
vibu@item-ax35755:~/work/foo$ helm dep up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Deleting outdated charts

vibu@item-ax35755:~/work/foo$ helm template .
---
# Source: foo/charts/boo/templates/test.yaml
fromParent:
  hello: from foo
fromSubchart:
  hello: from boo

  
vibu@item-ax35755:~/work/foo$ mv requirements.yaml{,.bak}
vibu@item-ax35755:~/work/foo$ helm template .
---
# Source: foo/charts/boo/templates/test.yaml
fromParent:
  hello: from foo

`

**Comment by vbuciuc** [comment]
@bacongobbler is there any intention of further addressing this in 2.x?

**Comment by paleg** [comment]
We also hit this issue (similar to described by @vbuciuc) with not working "null" for values override when subchart listed as a dependency in requirements.yaml with 3.2.1 and 3.2.0. Previous version (3.1.x) works as expected.

**Comment by Chili-Man** [comment]
@bacongobbler  @technosophos  I'm running into this issue as well with Helm `3.3.4`, can you please re-open; 

I can confirm that it worked in `3.1.2` and it stopped working after `3.2.x` as @paleg mentions.  For now, it appears that @tuzla0autopilot4 's workaround of setting it to a non-map value like `false` will produce the intended behavior but does give output warnings when that is done.

**Comment by AntonOfTheWoods** [comment]
@Chili-Man , I have just tried with `3.1.3` and it doesn't seem to work. It will apply with `null` but I get a warning and it doesn't do anything. With anything else (`false`, `0`, `[]`) it refuses with (e.g.,)

```coalesce.go:196: warning: cannot overwrite table with non table for resources (map[requests:map[cpu:250m memory:256Mi]])
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
postgresql:
- resources: Invalid type. Expected: object, given: boolean
```
(or what the type that I try that is not a dict/hash). With `3.3.4` I get just silence and it does nothing with `null` and likewise everything else refuses to apply. Most annoying...

**Comment by JeroenVanOort** [comment]
I'm still experiencing this issue in 3.4.2.

**Comment by BohdanKalytka** [comment]
The issue is still present in 3.4.2, but only in certain situations.
I have a chart with multiple sub-charts.
When putting default into sub chart values `null` override does not work. If you move the same values into parent chart values it works as expected.
This is reproducible only with sub-charts. When you put it in a single (flat) chart everything works fine.

**Comment by alexrashed** [comment]
I am experiencing the same problem when using subcharts (as described by @BohdanKalytka above).
In my case I want to overwrite the securityContext when using the [ElasticSearch helm chart](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/openshift/values.yaml) in an OpenShift cluster.
Is this issue going to be reopened, or should we create a new one?

**Comment by elliotkennedy** [comment]
Raised #9136

**Comment by MatteoInfi** [comment]
still bugged in 3.5.4

**Comment by armandleopold** [comment]
Still exist in  

```
HELM_VERSION="v3.6.3"
```
Can someone reopen the issue and fix it please ?

**Comment by kineta-Jiang** [comment]
Still exist in

`HELM_VERSION="v3.7.1"`
Can someone reopen the issue and fix it please ?

**Comment by sebastianblunt** [comment]
The reopened issue is https://github.com/helm/helm/issues/9136

**Comment by scalalang2** [comment]
Still exist in v3.7.2

**Comment by hosswald** [comment]
Still exists in v3.9.2

**Comment by kopylash** [comment]
Still exists in 3.11.1
Reproducible only with subcharts

**Comment by korniltsev** [comment]
still exists in 3.12.3

**Comment by korniltsev** [comment]
repro:
[pyroscope-folder.zip](https://github.com/helm/helm/files/12585834/pyroscope-folder.zip)
fsGroup and runAsUser null values are not removed
```
helm upgrade release-1 pyroscope-folder  --dry-run  --install > run1   
helm upgrade release-1 pyroscope-folder --values pyroscope-folder/values.yaml --dry-run  --install > run2 

diff -u run1 run2
--- run1        2023-09-12 18:26:31.238211712 +0700
+++ run2        2023-09-12 18:27:28.071648302 +0700
@@ -1,6 +1,6 @@
 Release "release-1" does not exist. Installing it now.
 NAME: release-1
-LAST DEPLOYED: Tue Sep 12 18:26:26 2023
+LAST DEPLOYED: Tue Sep 12 18:26:51 2023
 NAMESPACE: default
 STATUS: pending-install
 REVISION: 1
@@ -194,9 +194,7 @@
     spec:
       serviceAccountName: release-1-pyroscope
       securityContext:
-        fsGroup: 10001
         runAsNonRoot: true
-        runAsUser: 10001
       containers:
         - name: "pyroscope"
           securityContext:

```

**Comment by ccmcbeck** [comment]
> still exists in 3.12.3

While I was unable to override a default subcharted value with `foo: nil`, I was able to override with `foo: ""`.

**Comment by bauerjs1** [comment]
Still having this issue in Helm v3.13.2. Unfortunately I cannot use @ccmcbeck's workaround, because the particular value is not fenced with an `if` in the template and the value must be of type integer.

Overwriting the default value with `null`/`nil` (which does not work atm) is the only option I see here.

**Comment by rodrigoechaide** [comment]
I have created a new [issue](https://github.com/helm/helm/issues/12637) because this problem persists in the latest version of Kubernetes.
