### ISSUE TITLE
Helm upgrade not upgrading deployment when time out waiting for condition

### ISSUE THREAD

**Issue by newwdles** [helm/helm#5939]
Hello, 

When helm upgrade fails because of a timeout while waiting for the deployement, subsequent upgrade seems to generate a delta between the data stored in helm ConfigMap and what's truly deployed in kube, resulting in an impossibility to deploy a change.

Step to reproduce :

1. Initial deployement (everything ok)
`helm upgrade --install --namespace mynamespace --kube-context mykubecontext --wait -f myvalue.yaml --timeout 180 release-name charts/chart-name`

(i have omited parameters and names for the sake of clarity)
...
`STATUS: DEPLOYED`
...

2. Change something that prevent the container from successfully starting, i choose to reduce the readiness and liveness probe to something too short, but in real life it may be an application failing to start for whatever reason.

```
deployment:
  readinessProbe:
    initialDelaySeconds: 70
    periodSeconds: 2
    failureThreshold: 30
  livenessProbe:
    initialDelaySeconds: 130
    periodSeconds: 2
    failureThreshold: 3
```
Changed to 

```
deployment:
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 1
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 1
```
(yes, the application is quite long to start)

3. Upgrade again :
`helm upgrade --install --namespace mynamespace --kube-context mykubecontext --wait -f myvalue.yaml --timeout 180 release-name charts/chart-name`

This time the upgrade fails while waiting (as expected) :
```
UPGRADE FAILED
Error: timed out waiting for the condition
Error: UPGRADE FAILED: timed out waiting for the condition
```

4. Fix the probe :

```
deployment:
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 1
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 1
```
Back to :
```
deployment:
  readinessProbe:
    initialDelaySeconds: 70
    periodSeconds: 2
    failureThreshold: 30
  livenessProbe:
    initialDelaySeconds: 130
    periodSeconds: 2
    failureThreshold: 3
```

5. Upgrade one last time :
`helm upgrade --install --namespace mynamespace --kube-context mykubecontext --wait -f myvalue.yaml --timeout 180 release-name charts/chart-name`

The upgrade fails again (unexpectedly) :
```
UPGRADE FAILED
Error: timed out waiting for the condition
Error: UPGRADE FAILED: timed out waiting for the condition
```

Deployment inside kube is still on the bogus probe timings :
```
kubectl describe deployments. release-name | grep delay
    Liveness:   http-get http://:8080/actuator/health delay=5s timeout=1s period=2s #success=1 #failure=1
    Readiness:  http-get http://:8080/actuator/health delay=5s timeout=1s period=2s #success=1 #failure=1
```

Helm data are good :
```
helm get release-name  | grep Delay
    initialDelaySeconds: 130
    initialDelaySeconds: 70
            initialDelaySeconds: 130
            initialDelaySeconds: 70
```
Helm history :
helm history release-name
```
REVISION	UPDATED                 	STATUS  	CHART                  	DESCRIPTION                                                 
1       	Tue Jun 25 11:23:28 2019	DEPLOYED	mychart-1.0.0	Install complete                                            
2       	Tue Jun 25 11:25:45 2019	FAILED  	mychart-1.0.0	Upgrade "release-name" failed: timed out...
3       	Tue Jun 25 11:29:40 2019	FAILED  	mychart-1.0.0	Upgrade "release-name" failed: timed out...
```

Using --atomic solves the problem but it's not quite the behavior we want.

I can provide more details if necessary.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.10", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-06-19T20:11:19Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by alistaircross** [comment]
Did you happen to figure this one out?

**Comment by vzabawski** [comment]
I have the same issue after deploying a pod with wrong repository specified for container. It still deploys old value, although the value in chars was fixed.

**Comment by vzabawski** [comment]
Fixed this issue with the command from this comment:
https://github.com/helm/helm/issues/3208#issuecomment-352241117

**Comment by dudicoco** [comment]
Is there a solution for this issue? Deleting the release is not a viable option.

**Comment by jmril-srcclr** [comment]
The same issue after deploying a pod with wrong repository specified for the container and the helm release failed.

**Comment by octanolab** [comment]
+1

**Comment by bgcorreia** [comment]
+1

**Comment by brainbug89** [comment]
Any updates on this issue?

**Comment by dudicoco** [comment]
This is fixed in https://github.com/helm/helm/pull/7653 which is included in `v3.2.1`.

**Comment by amirschw** [comment]
@dudicoco @bacongobbler I believe #7653 only allows previously failed releases to be upgraded **when there have been no successful releases**. It doesn't solve the case brought up in the issue, of subsequent deployments after `helm upgrade` fails with "timed out waiting for the condition". Can this be reopened?

**Comment by yacinelazaar** [comment]
@dudicoco did you manage to get this solved.
Im experiencing this in v3.5.2.

**Comment by dudicoco** [comment]
@yacinelazaar are you experiencing this exact bug? I've been experiencing another similar bug in the newer helm version, that happens when the deployment was canceled/interrupted in the middle.

**Comment by yacinelazaar** [comment]
@dudicoco I'm running upgrade with `--atomic`. When the release fails, the rollback to a successful release also fails (yet I have a successful release in history).

**Comment by dudicoco** [comment]
@yacinelazaar I would search the issues here for a similar issue, there are a few issues related to upgrading failed releases.
