### ISSUE TITLE
`hook-delete-policy: hook-succeeded` does not work with Helm 2.15 anymore

### ISSUE THREAD

**Issue by ckoenig** [helm/helm#6741]
Output of `helm version`:

    $ helm version
    Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

Output of `kubectl version`:

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-gke.0", GitCommit:"569511c9540f78a94cc6a41d895c382d0946c11a", GitTreeState:"clean", BuildDate:"2019-08-21T23:28:44Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

After an upgrade to Helm 2.15 our `pre-install`/`pre-upgrade` hooks did not work as expected anymore. We are creating `Job`s to run upfront. The job got created and immediately deleted, a pod for the job could be seen, too, but it immediately seems to end up in the Terminating state. So Helm didn't really wait for the pod to start running and/or succeed.

As a solution we simply replaced

    "helm.sh/hook-delete-policy": hook-succeeded

with

    "helm.sh/hook-delete-policy": before-hook-creation

In that case the job actually gets executed, but AFAICS it's not really waiting for the job to finish, but continues with the rest of the installation/upgrade of the chart immediately.

**Comment by jyotirbhandari** [comment]
Same issue can be seen after upgrading to helm v2.15, using hook-succeed shows pod geting terminated without appropriate logs.

**Comment by jyotirbhandari** [comment]
Temporary Solution till the fix is in place.

Server side
```
helm reset --force
helm init --service-account tiller --tiller-image gcr.io/kubernetes-helm/tiller:v2.14.3
```

Client or CI/CD
```
 curl -L https://git.io/get_helm.sh  |bash -s -- --version v2.14.3
```

**Comment by bcorijn** [comment]
Looks like I have a similar issue here, my post-upgrade/install hooks with hook-succeeded deletion policy don't seem to fire correctly anymore after upgrading to Helm 2.15.

**Comment by thomastaylor312** [comment]
So many of these reported hook issues may all be resolved by a recently merged fix #6897. Can anyone give the `dev-2` branch a try and see if it fixes it for them?

**Comment by bacongobbler** [comment]
While I don't have a chart which I can use to verify the behaviour locally, I'm fairly certain this has been fixed in #6897. That patch fixes an issue with the kube client unable to wait for Jobs to run to completion as seen in #6894. Kubernetes 1.16 introduced a breaking change to the legacy schema so we had to update the code to reflect that change.

I'm going to close this as tentatively resolved via #6897, which will be in Helm 2.16.1. Please feel free to report your findings once 2.16.1 has been released with the likely fix mentioned above and we'll re-open if this is still an issue in 2.16.1+. I'm interested to hear your findings!

**Comment by thomastaylor312** [comment]
I am pretty certain that this should be solved by #6907. @ckoenig you are correct in that it wasn't waiting for certain jobs (see the explanation in the linked PR). Going to leave this closed for now as the PR is now open. If that PR does not resolve the issue, please let us know

**Comment by GuillaumeCisco** [comment]
Fixed with v2.16.1

**Comment by olakunleoladimeji** [comment]
still having this issue with the stable/minio chart.

Helm version: 2.16.7
