### ISSUE TITLE
crd-install apiextensions.k8s.io/v1 does not work

### ISSUE THREAD

**Issue by strainovic** [helm/helm#6783]
https://github.com/helm/helm/blob/0a9bf4f966726f0bb0faa6a82db29909abe16126/pkg/kube/client.go#L597

Helm version: 2.15.1

```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

Kubernetes version: 1.16.2

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Kubernetes distribution: Canonical Microk8s

I've tried to deploy CRD with new apiextensions.k8s.io/v1 API but once I add "helm.sh/hook": crd-install installation failed with error "unable to convert to CRD type...".

```
Error: unable to convert to CRD type: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65"
```

apiextensions.k8s.io/v1beta1 is depricated in 1.16 and will be removed in 1.19.

How much is it likely for this bug to be fixed in 2.x version?

Thanks

**Comment by thomastaylor312** [comment]
@strainovic Thanks for reporting this. So just to double check, apiextensions v1 is new in 1.16 right? If so, this would be a bug we should fix and we would have to update our version of client-go.

**Comment by thomastaylor312** [comment]
Actually I just found it in the release notes. Look like we will need to update client-go for both v2 and v3: https://kubernetes.io/docs/setup/release/notes/#api-changes

**Comment by bacongobbler** [comment]
fixed in #6808 for Helm 3, and #6810 for Helm 2.

**Comment by strainovic** [comment]
After upgrade to 2.16.1 bug is still here :(

```
helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

```
Error: unable to convert to CRD type: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:67"
```

I use helm.sh/hook: "crd-install" annotations to install my CRD.

**Comment by lsoica** [comment]
Same here. with 2.16.1.

So why is this closed ?

**Comment by remzi-e** [comment]
I had the same issue with 2.16.1.
Can we please reopen this? @bacongobbler

**Comment by bacongobbler** [comment]
What version of Kubernetes are you running on? It’s possible this API is unavailable if you’re using an older version of Kubernetes

**Comment by remzi-e** [comment]
tried with 1.16.3 and 1.17.2

**Comment by bacongobbler** [comment]
Weird. Okay, I’ll go ahead and reopen this. Please let us know if you find anything interesting.

**Comment by caseydavenport** [comment]
Is this just because only the v1beta1 version of the API is added to the scheme? https://github.com/helm/helm/blob/release-2.16/pkg/kube/client.go#L88

I don't see anywhere that does the same for apiextensions/v1

**Comment by thomastaylor312** [comment]
Yeah, that is likely the problem. We'll need to port that to the dev-v2 branch

**Comment by bacongobbler** [comment]
Good catch, @caseydavenport. Yes, that appears to be the case.

**Comment by bacongobbler** [comment]
Gentle reminder that the support window for bugfixes closes in a month. If nobody works on this, we'll have to close this out and consider this as Helm 2 only supporting the apiextensions v1beta1 API.

**Comment by jimmidyson** [comment]
I've pushed #8460 that fixes this - hope we can merge soon ready for a new 2.x release.

**Comment by mattfarina** [comment]
Removed from milestone as it is not ready and the release is going out.

**Comment by bacongobbler** [comment]
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.

**Comment by Xtigyro** [comment]
@mattfarina @bacongobbler 

Gentlemen - any chance the fix can go in Helm v2.17?

**Comment by bacongobbler** [comment]
@Xtigyro see https://github.com/helm/helm/issues/6783#issuecomment-674171578.

**Comment by Xtigyro** [comment]
I hoped the already written fixes might sneak in, huh. 

Thanks for your reply, @bacongobbler!

**Comment by bacongobbler** [comment]
#8460 [required more work](https://github.com/helm/helm/pull/8460#discussion_r463114739) before it could be merged, so it was not in a state to be merged into Helm core. We [asked for an update](https://github.com/helm/helm/pull/8460#issuecomment-670027274) and the author mentioned they would not be able to work on it further.

We announced plans to deprecate Helm 2 over a year ago, and the merge window for Helm 2 bug fixes passed a little under 6 months ago, so it's a little late for that.
