### ISSUE TITLE
I want to try use helm v3 but met some problems

### ISSUE THREAD

**Issue by andyzheung** [helm/helm#6885]
![image](https://user-images.githubusercontent.com/22912347/68187656-2b8f1580-ffe2-11e9-93b5-098e692a57df.png)

![image](https://user-images.githubusercontent.com/22912347/68187741-5f6a3b00-ffe2-11e9-8bed-b5f21a41954f.png)

**Comment by bacongobbler** [comment]
Hi @andyzheung, as the error suggests, it would appear that your kubernetes cluster is unreachable. Your Kubernetes instance could be down, or your network setup is incorrect, or your local setup (your kube config) is misconfigured. What is the output of `kubectl cluster-info`?

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/4b462c39022993a8687bfc44df308534cf1cc306/pkg/kube/client.go#L75-L83

**Comment by andyzheung** [comment]
> https://github.com/helm/helm/blob/4b462c39022993a8687bfc44df308534cf1cc306/pkg/kube/client.go#L75-L83

![image](https://user-image@bacongobbler .githubusercontent.com/22912347/68191591-d572a000-ffea-11e9-9812-65d279faeec7.png)

It seem to running at 6443 port.
@bacongobbler

**Comment by andyzheung** [comment]
It seem to running at 6443 port.
@bacongobbler 
![image](https://user-images.githubusercontent.com/22912347/68191683-06eb6b80-ffeb-11e9-9eb9-27d3eaa0f1eb.png)

**Comment by andyzheung** [comment]
And my other k8s cluster is 16443 port..
Can I change the port of helm connect?
![image](https://user-images.githubusercontent.com/22912347/68191831-5893f600-ffeb-11e9-96ee-47b860b89e36.png)

**Comment by Mikedu1988** [comment]
no, you can't
helm use kubeconfig to access the cluster, if helm is install on the same node of your second cluster, it should be working. 
If helm is installed on other hosts, you need to get a working kubeconfig file first, make sure you can use kubectl to access the cluster

**Comment by andyzheung** [comment]
My cluster can use kubectl to access.
my kubeconfig.yaml
![image](https://user-images.githubusercontent.com/22912347/68194466-0dc8ad00-fff0-11e9-9636-2f2854098a13.png)

**Comment by andyzheung** [comment]
It seems I use the kubeconfig file which my kubelet use that still don't work.
![image](https://user-images.githubusercontent.com/22912347/68197243-dc061500-fff4-11e9-926c-fcac65177b32.png)

**Comment by bacongobbler** [comment]
If you can provide a set of steps on how to reproduce this issue, that would be helpful to diagnose the issue. Currently if I boot up a cluster with `minikube start`, Helm will work right out of the box.

**Comment by andyzheung** [comment]
I just use two way to run k8s:
1、k3s:
https://github.com/rancher/k3s
2、microk8s:
https://microk8s.io/docs/

and them just install helmv3:
wget https://cloudnativeapphub.oss-cn-hangzhou.aliyuncs.com/helm-v3.0.0-alpha.1-linux-amd64.tar.gz
tar -xvf helm-v3.0.0-alpha.1-linux-amd64.tar.gz
mv linux-amd64 helm3
mv helm3/helm helm3/helm3
chown root.root helm3 -R
cat > /etc/profile.d/helm3.sh << EOF
export PATH=$PATH:/home/andy/helminstall/helm3
EOF
source /etc/profile.d/helm3.sh


helm repo add apphub https://apphub.aliyuncs.com

helm search repo guestbook

helm install guestbook apphub/guestbook --set service.type=NodePort

**Comment by hickeyma** [comment]
@andyzheung It seems that you are using `v3.0.0-alpha.1` which is a very early version of Helm 3 unreleased. Do you mind using the latest which is [Helm 3 RC-2](https://github.com/helm/helm/releases/tag/v3.0.0-rc.2) and test again?

**Comment by KinoshitaShimizu** [comment]
I am also having exactly the same issue with a new k3os instance.

I used Helm 3 RC-2.

The k3os instance is working perfectly, I can run machines on it and have had no connection problems. The kubeconfig file is also perfectly fine.

![image](https://user-images.githubusercontent.com/25405969/68308612-c2a3ae00-0072-11ea-996d-1a677fe79e4d.png)

**Comment by KinoshitaShimizu** [comment]
Oh, I found how to make it work! I have to specify manually the kubeconfig file using the flag, like this:

```bash
helm install runner gitlab/gitlab-runner -f /home/rancher/.gitlab/values.yaml --kubeconfig /etc/rancher/k3s/k3s.yaml
```
After 8 hours trying to make it work... finally it succeeds...

![image](https://user-images.githubusercontent.com/25405969/68310523-c7b62c80-0075-11ea-8c69-90aaf5bb82bb.png)

**Comment by bacongobbler** [comment]
Closing as an issue on the user's end with how the cluster is configured. Nothing actionable on our end here.

**Comment by andyzheung** [comment]
> @andyzheung It seems that you are using `v3.0.0-alpha.1` which is a very early version of Helm 3 unreleased. Do you mind using the latest which is [Helm 3 RC-2](https://github.com/helm/helm/releases/tag/v3.0.0-rc.2) and test again?

Thank you so much, I use  Helm 3 RC-2 and test like this:
![image](https://user-images.githubusercontent.com/22912347/68521395-a6567a00-02db-11ea-8ebb-6f124e936fd1.png)

It works .
@KinoshitaShimizu @hickeyma 

But Helm 3 RC-1 still not work.. may be some bug in this version.  @hickeyma 

Any way , I will use RC-2 to test.
