### ISSUE TITLE
Pre-Release ignored on helm repo update

### ISSUE THREAD

**Issue by fabianschwarzfritz** [helm/helm#6957]
Hi,

we have our own helm chart repository and deploy pre-releases, built on a CI server. These pre-releases do not appear when searching the repository. 

**Questions**
Is this behavior on purpose? 
Is it somehow possible to also sync pre-release versions of helm charts, and install them withour explicitly setting the version? 

we have a development setup where the local developers installs the latest version to be found from the helm chart we are developing to his local docker-desktop/cluster/minikube. Then, one can do modifications to the deployments and more to bring local changes to the deployment.

**More background**
Our CI job updates the  `master` commit to a chart called "xxxxxxxx-0.1.0-dev". This version is included in semver, see the official semver [documentation for pre-releases](https://semver.org/#spec-item-9).  The chart in this version is not listed when searching the chart: `helm search repo yyyyyyy --version`. Every developer has to explicitly specify the version with `helm install ...... --version 0.1.0-dev".

Output of `helm version`:
```bash
>> helm version
version.BuildInfo{Version:"v3.0.0-rc.3", GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```bash
>> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Docker for Desktop.

**Comment by hickeyma** [comment]
`install` will use the latest version of the chart in the repository. 

When searching the repo, has that chart version being added to the repo?

**Comment by fabianschwarzfritz** [comment]
Hi @hickeyma 
sorry for the missing information. To prevent a misunderstanding, I do the following. I have to add placeholders for the repositories, as it is company internal (i use my-repo and my-chart). 

```bash
>> helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "my-repo" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

```bash
>> helm search repo my-repo --version 
my-repo/my-release                  	0.0.1        	DEVEL      	Some description
```

The index yaml on for our repository look like this: 
```

  my-release:
  - apiVersion: v1
    appVersion: DEVEL
    created: 2019-11-08T16:36:03.014Z
    name: my-release
    urls:
    - local://my-release-0.1.0-dev.tgz
    version: 0.1.0-dev
     ...
  - apiVersion: v1
    appVersion: DEVEL
    created: 2019-08-13T14:03:26.705Z
    name: my-release
    version: 0.0.1
    ...
  - apiVersion: v1
    appVersion: DEVEL
    created: 2019-09-30T12:36:20.411Z
    name: my-release
    urls:
    - local://my-release-0.0.1-debug.tgz
    version: 0.0.1-debug
     ...
```

sorry again for not being able to give you the original, and for having to "blacken" the original files and terminal output.

Let me know in case more output is needed.

Thanks and best regards,
Fabian

**Comment by bacongobbler** [comment]
Can you please test with 3.0.0? This has been fixed in later releases. RC.4 if I'm not mistaken.

**Comment by fabianschwarzfritz** [comment]
I retried and used the freshly release helm3 version and still have the same issue. 
This is the helm cli version I used:

```bash
helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Comment by felixkl** [comment]
I am also having this issue. The chart file are present on the repo and in the index.yaml. They can also be installed by specifying that exact pre-release version via `--version`. But in the `helm search repo` result the pre-release versions are not listed. I am using:
```
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**Comment by bacongobbler** [comment]
have you tried `helm search repo --devel`? Pre-release versions are hidden by default.

**Comment by fabianschwarzfritz** [comment]
Hi @bacongobbler ,

thanks for this hint! There exist two commands, `helm repo search`, and `helm search repo` and the latter has the option you described `--devel` and it returns pre-releases as well. 

Thanks for clarifying!

Cheers,
Fabian
