### ISSUE TITLE
[helm3] helm template with --output-dir doesn't write hook and still print stdout

### ISSUE THREAD

**Issue by ruruiye** [helm/helm#7001]
Output of `helm version`:
3.0.0

Output of `kubectl version`:
v1.16.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

helm 3 with command `helm template . --output-dir ~/tmp` doesn't include the hook resources. and still print to stdout.

```
helm template . --output-dir ~/tmp/demp-output
wrote /home/ruruiye/tmp/demp-output/demo/templates/deployment.yaml


---
# Source: demo/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
xxx
```

previously with helm 2, the output will include these hooks:

```
helm2 template . --output-dir ~/tmp/demp-output 
wrote /home/ruruiye/tmp/demp-output/demo/templates/configmap.yaml
wrote /home/ruruiye/tmp/demp-output/demo/templates/tests/test-connection.yaml
wrote /home/ruruiye/tmp/demp-output/demo/templates/deployment.yaml
wrote /home/ruruiye/tmp/demp-output/demo/templates/job.yaml
```

**Comment by ruruiye** [comment]
the template command is totally wrong. currently it's implement in `pkg/action/install.go`, but the output is print in `cmd/helm/template.go`, so it never close the output to stdout and the write to file is also missing the hook. I am trying to fix this but it's not a easy fix since the down side api only return rendered manifest and no way to split them up again.

**Comment by JeroenRijks** [comment]
I'm having the same issue as you, and am happy to help by reviewing/testing anything

**Comment by ruruiye** [comment]
this is fixed in the new version of helm 3.1.0, so I will close this now.

**Comment by nWhitehill** [comment]
I'm still seeing this issue with helm version:
`version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Comment by NorthFuture** [comment]
And it's still present with helm version:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Comment by obolobova** [comment]
Same problem for me in 3.1.2.

**Comment by tredmon** [comment]
Still present in 3.2.0

**Comment by nathan-clark** [comment]
is this to be fixed?

**Comment by bacongobbler** [comment]
@ruruiye can you explain how this was fixed in Helm 3.1.0?

**Comment by yeluolei** [comment]
Sorry, maybe I am wrong with the result.

**Comment by ruruiye** [comment]
Sorry, maybe I am wring with the behavior, it’s long time ago.

**Comment by bacongobbler** [comment]
fixed in https://github.com/helm/helm/pull/8156, which will be available in Helm 3.3.0.
