### ISSUE TITLE
[helm3] `helm create` with custom starter will strip all comments and new line.

### ISSUE THREAD

**Issue by m31271n** [helm/helm#7012]
# Helm Version
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

# OS Version
```
macOS 10.14.6
```

# Bug Reproduce
Create a fresh starter from official template via following script:

```sh
#!/usr/bin/env bash
set -e

BASE_TEMPLATE_DIR=_official
HELM_VERSION=$(command helm version -c --short)

# create base template via Helm default starter
helm create XXXXX
find XXXXX -type f -exec sed -i 's/XXXXX/<CHARTNAME>/g' {} \;

rm -rf "$BASE_TEMPLATE_DIR"
mv XXXXX "$BASE_TEMPLATE_DIR"

# track version of Helm
echo "$HELM_VERSION" > "$BASE_TEMPLATE_DIR"/helm-version
```

Put it in `starters` folder. I'm using macOS, so the folder will be `~/Library/helm/starters` by default:

```sh
mv _official ~/Library/helm/starters
```

Create a charts from above starter:
```sh
helm create --starter _official fake_app
```

Inspect the output files, take `fake_app/values.yaml` as an example: 
```yaml
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []
```

You can see, the comments and new lines are striped.

**Comment by TomasKohout** [comment]
I had the same problem... I dirty fixed that with moving my values.yaml and Chart.yaml into the templates folder. After helm create I moved them one folder upper. :-) 

But it is not a good practice. :)

**Comment by TBBle** [comment]
Probably the same underlying issue as #6951, that during this process the values.yaml is parsed and then marshalled back into YAML, which has the effect of stripping comments and alphabetising the contents.

**Comment by cdrage** [comment]
Duplicate of https://github.com/helm/helm/issues/6951 @bacongobbler

**Comment by bacongobbler** [comment]
different code path, same result

**Comment by bacongobbler** [comment]
fixed in #7201

**Comment by jslay88** [comment]
This should be reopened, as it still persists as an issue with `Chart.yaml`
