### ISSUE TITLE
How to achieve a good level of verbosity with `helm ... --wait` ?

### ISSUE THREAD

**Issue by pikapika2020** [helm/helm#7760]
I want to achieve a good level of verbosity with `helm --wait`. Its output is completely silent. I want to have same strings as with `--debug` flag, but without YAMLs being printed

`helm upgrade --wait --install --set test=guest  --debug test .`:
```
upgrade.go:90: [debug] performing update for test
upgrade.go:232: [debug] creating upgraded release for test
client.go:163: [debug] checking 2 resources for changes
client.go:403: [debug] Looks like there are no changes for ConfigMap "test1"
client.go:403: [debug] Looks like there are no changes for ConfigMap "test2"

...computed values, YAMLs and so on...
```

`-v 6` and so on does not give me what would be preferrable

It would be great if with `--wait` flag it printed out something like:
```
[wait] checking these resources for changes:
[wait] <blah blah blah>
[wait] patching resource ConfigMap test1
[wait] ...
[wait] all resources ready
[wait] ... etc.
```

**Comment by seandilda** [comment]
I would like to second this.  Having an option to give the current debug output minus the rendered yaml files would be very helpful.

**Comment by smueller18** [comment]
As a workaround I currently use grep to filter only release summary output and ignore rendered template output (but it is also possible, that some lines in the rendered template output could match). The debug output before the release summary is printed on stderr so it is not filtered by grep at all.

```bash
helm upgrade -i --debug --wait release-name . \
  | grep -E "(Happy\ Helming|NAME\: |LAST DEPLOYED\: |NAMESPACE\: |STATUS\: |REVISION\: | TEST SUITE\: )" \
    --color=never || true
```

An example output would look like

```
history.go:52: [debug] getting history for release kured
upgrade.go:121: [debug] preparing upgrade for kured
upgrade.go:129: [debug] performing update for kured
upgrade.go:308: [debug] creating upgraded release for kured
client.go:173: [debug] checking 10 resources for changes
client.go:431: [debug] Looks like there are no changes for PodSecurityPolicy "kured"
client.go:431: [debug] Looks like there are no changes for ServiceAccount "kured"
client.go:431: [debug] Looks like there are no changes for ConfigMap "grafana-dashboards-kured"
client.go:431: [debug] Looks like there are no changes for ClusterRole "kured"
client.go:431: [debug] Looks like there are no changes for ClusterRoleBinding "kured"
client.go:431: [debug] Looks like there are no changes for Role "kured"
client.go:431: [debug] Looks like there are no changes for RoleBinding "kured"
client.go:431: [debug] Looks like there are no changes for DaemonSet "kured"
wait.go:53: [debug] beginning wait for 10 resources with timeout of 10m0s
upgrade.go:136: [debug] updating status for upgraded release for kured
Release "kured" has been upgraded. Happy Helming!
NAME: kured
LAST DEPLOYED: Sat May 30 00:28:20 2020
NAMESPACE: kube-system
STATUS: deployed
REVISION: 19
```

Because this is not a very nice workaround, I would love to see this functionality implemented natively in helm.

**Comment by blafasel42** [comment]
instead of the whole grep stuff, i tried with: `| sed -n '/USER-SUPPLIED VALUES:/q;p' `  which seems to  work as well.

**Comment by desaintmartin** [comment]
I would love to see such a feature. We use --debug only to follow progress during --wait installs, so it is too verbose for what we need.

**Comment by bacongobbler** [comment]
for reference, https://github.com/helm/helm/issues/2044 was closed due to inactivity.

**Comment by desaintmartin** [comment]
What should be the answer for this?
Today, log is only printed in debug mode in stderr.

Should we put it to stdout without requiring the debug flag (i.e show it by default)? Should we add yet another flag (in order not to be breaking in the case people rely on output analysis)?

I suppose this is really easy to change, I'll try to find time for this.

**Comment by adrienjt** [comment]
This [PR comment](https://github.com/helm/helm/pull/8582#issuecomment-699177550) also applies here, to discuss the alternative solution that I propose, with spinners, in stderr.

**Comment by bacongobbler** [comment]
If someone wants to take over https://github.com/helm/helm/pull/8582 but display log messages on stderr, feel free. https://github.com/helm/helm/pull/8582 went stale due to inactivity from the author, but it's heading in the right direction.

For future contributors: I'd also suggest writing unit tests to ensure the code works as expected.

**Comment by jdomag** [comment]
Would love to see that feature. Unfortunately all my password rendered from env vars are visible in CI/CD system now :/ 
Also usage of sed or grep has side effect  - if you check if helm upgrade completed based on command exit code it will be overridden by pipe command.

**Comment by jmcelwain** [comment]
@bacongobbler I'd like to revive this. Do you think this needs a separate flag in order to be backwards compatible? #2044 didn't seem to address if that was a requirement.

**Comment by mkreidenweis-schulmngr** [comment]
unstale please :-)
would be really nice feature

**Comment by Tom910** [comment]
I found kubedog which help resolve this issue - https://github.com/werf/kubedog/blob/master/doc/usage.md#multitracker-cli - verbose logs and status + show pods log

**Comment by jwenjian** [comment]
`--wait` should at least having a spinner to indicates that the command is running

**Comment by nikban95** [comment]
Hi team.. 
Did it got picked up. Don't want my passwords to be visible in my cicd pipeline.

**Comment by sreich** [comment]
I have implemented helm into our CICD's as well and this is the biggest feature I'd like to see from helm. Nice progress, prettyable, and filterable on different levels would be perfect 😋

**Comment by sreich** [comment]
So, this problem still exists, can we get this re-opened? 

I also tried --debug to give myself more info but helm starts outputting to stderror for debug

I think helm needs to improve their logging and return hooks. I should be able to set a script to monitor stderr result for if the install/upgrade worked or failed. Adding --debug breaks that. And --wait gives me no progress or any indication at all until it fails.

@bacongobbler

**Comment by maratori** [comment]
It's unfortunate that we are still missing such a fundamental feature.

**Comment by josegonzalez** [comment]
@jdomag you can enable pipefail to have the `| sed` call respect the exit code of helm:

```shell
set -o pipefail
```

I usually pair this with `set -e` to ensure the entire script fails immediately:

```shell
set -eo pipefail
```
