### ISSUE TITLE
`helm version` prints warning if kubeconfig file does not exist

### ISSUE THREAD

**Issue by unguiculus** [helm/helm#7796]
`helm version` prints a warning if the kubeconfig file does not exist.

```
KUBECONFIG=config-does-not-exist helm version
W0323 20:15:03.896373   34520 loader.go:223] Config not found: config-does-not-exist
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

This is especially problematic when the short version is used and parsed using a semver library.

```
KUBECONFIG=config-does-not-exist helm version --short
W0323 20:16:55.655484   34598 loader.go:223] Config not found: config-does-not-exist
v3.1.2+gd878d4d
```

The problem is that the Kubernetes client is always [initialized](https://github.com/helm/helm/blob/HEAD@%7B2020-03-23T19:32:00Z%7D/cmd/helm/helm.go#L87) which should not be necessary for the `version` command.

**Comment by bacongobbler** [comment]
Good catch. 

In the meantime, the warning message is displayed on standard error, so it can be stripped out by ignoring standard error:

```
><> KUBECONFIG=config-does-not-exist ./bin/helm version 2>/dev/null
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"a322199c65def15c5783eac9e49b7ffbf3bdb0a6", GitTreeState:"clean", GoVersion:"go1.14"}
```

**Comment by anshulvermapatel** [comment]
@unguiculus Really Its a good catch.

@bacongobbler , I can work on this. This seems to be a simple fix.

**Comment by donggangcj** [comment]
The warning log comes from https://github.com/kubernetes/kubernetes/blob/1c99825adfb30f6abb177e85ddb31f2fdef011e1/staging/src/k8s.io/client-go/tools/clientcmd/loader.go#L222.

**Comment by anshulvermapatel** [comment]
Well, I think the initialization of actionConfig is necessary but not for `help` and `version` command.
It can be solved if check if the argument is `help` or `version` then there is no need to initialize the actionConfig.
~~~
        helmDriver := os.Getenv("HELM_DRIVER")
	if os.Args[1] != "version" && os.Args[1] != "help" {
		if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), helmDriver, debug); err != nil {
			log.Fatal(err)
		}
	}
	if helmDriver == "memory" {
		loadReleasesInMemory(actionConfig)
	}
~~~

But I doubt if this is a correct way.
@mattfarina @hickeyma @bacongobbler @unguiculus  ← Anyone of you can give me a green signal for this, I can create a pull request for this.

**Comment by mattfarina** [comment]
@anshulvermapatel you are right that this isn't the best way. Here are a couple things I notice...

1. `os.Args[1]` is not always going to be the command. If a flag comes before the command it will be the first of those.
2. There are more commands than `help` and `version` that don't need the kubeconfig or even the action configuration. [You can see a list here](https://github.com/helm/helm/blob/97c68adc4d53c13fb32432010a8f7c5172e3549d/cmd/helm/root.go#L138-L172).
3. The API to `Init` needs to stay the same.
4. `Init` sets up things many commands need. For example, the logger.

I'm now thinking about loud on how to fix this. I wonder what @technosophos @bacongobbler @hickeyma and others think, too...

* Should the init work be moved to the function that creates the commands? For example, inside of `newInstallCmd`.
* What about more than one `Init` command for actions? For example, if only logging is needed an `InitLogging` that only does that.

This would move initialization to the commands and only initialize what's needed. I like this idea.

This is just thinking off the top of my head. In moving things around we need to make sure the Go API doesn't break semver for the major version.

**Comment by marckhouzam** [comment]
PR #6915 tries to limit the call to `actionConfig.Init()` to only those commands that need it.  It does so by creating a map of all relevant commands (https://github.com/helm/helm/pull/6915/files#diff-f1c3ff8851f4e702c61ff00f3d76583bR249).  I don't find that approach easy to maintain however, but I couldn't come up with another that would keep the call to `actionConfig.Init()` central.

Along the lines of @mattfarina's thoughts, I was wondering if it was possible to move the `actionConfig.Init()` command to within each command's `RunE()` call.  See the suggestion here: https://github.com/helm/helm/pull/6915#issuecomment-561172525

**Comment by anshulvermapatel** [comment]
@marckhouzam @mattfarina , I think creating a map is a brilliant idea and it is better that writing `actionConfig.Init()` in each commands' `RunE()` and also it is central.
~~~
$ ./helm version                                                                                                                  1 ↵
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"193850a9e2c509acf1a499d98e8d23c12c134f11", GitTreeState:"dirty", GoVersion:"go1.13.4"}
~~~
This was done by adding -
~~~
        subCmd, _, _ := cmd.Find(os.Args[1:])
	actionConfigRequired := action.ConfigRequired(subCmd)

	if actionConfigRequired {
		if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), helmDriver, debug); err != nil {
			log.Fatal(err)
		}
	}
~~~
Where `action.ConfigRequired(subCmd *cobra.Command)` is a function created in `action` package where it contains the map and set the Boolean for each command.

It works good. But, suppose if you give `--help` flag for any sub-command, it again gives the `Config not found` warning message.
~~~
$ ./helm list --help
W0402 03:09:37.872020  360090 loader.go:223] Config not found: aslkdfjasdf

This command lists all of the releases for a specified namespace (uses current namespace context if namespace not specified).
- - -
- - -
~~~

For this I tried adding the following -
~~~
	subCmd, str, _ := cmd.Find(os.Args[1:])
	actionConfigRequired := action.ConfigRequired(subCmd)

	for _, st := range str {
		if strings.Contains(st, "help") {
			actionConfigRequired = false
		}
	}
	if actionConfigRequired {
		if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), helmDriver, debug); err != nil {
			log.Fatal(err)
		}
	}
~~~
It checks if still any flag is help, and if any flag added after the subCommand and if it is help then it sets `actionConfigRequired` as false and the `actionConfig.Init()` does not get called.
~~~
$ ./helm list --help   
This command lists all of the releases for a specified namespace (uses current namespace context if namespace not specified).
- - -
- - - 
~~~

Let me know your views on this. 
Thanks.

**Comment by technosophos** [comment]
I believe this issue is solved by #7831

**Comment by anshulvermapatel** [comment]
@technosophos , I cloned the repo, switched to that branch and build it. I still see the warning message.
~~~
╭─ansverma@localhost ~/contribution/helm/7796/helm_pull_7831/helm/bin ‹kubernetes-1.18› 
╰─$ kubectl version                  
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
╭─ansverma@localhost ~/contribution/helm/7796/helm_pull_7831/helm/bin ‹kubernetes-1.18› 
╰─$ ./helm version    
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"313289b5b66a9e1ebce254d3c0744ac01ebdf200", GitTreeState:"clean", GoVersion:"go1.13.4"}
╭─ansverma@localhost ~/contribution/helm/7796/helm_pull_7831/helm/bin ‹kubernetes-1.18› 
╰─$ export KUBECONFIG=something_senseless
╭─ansverma@localhost ~/contribution/helm/7796/helm_pull_7831/helm/bin ‹kubernetes-1.18› 
╰─$ ./helm version                       
W0402 16:26:10.131630  423438 loader.go:223] Config not found: something_senseless
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"313289b5b66a9e1ebce254d3c0744ac01ebdf200", GitTreeState:"clean", GoVersion:"go1.13.4"}
╭─ansverma@localhost ~/contribution/helm/7796/helm_pull_7831/helm/bin ‹kubernetes-1.18› 
╰─$ ./helm help   
W0402 16:26:19.521030  423464 loader.go:223] Config not found: something_senseless
The Kubernetes package manager

Common actions for Helm:
- - - 
- - - 
~~~

**Comment by technosophos** [comment]
Okay. @adamreese and I will look at this today. For sure, his patch will change the underlying code that the above calls, but we may need to just add one more guard.

**Comment by technosophos** [comment]
Okay, so this error occurs _only_ when you set the `KUBECONFIG` environment variable to a non-existent path. If you `unset KUBECONFIG`, it is fine. If you set `KUBECONFIG=""` it is fine. The warning message ONLY prints when you give it an invalid path for KUBECONFIG.

_Why do you believe it is a bug that if you supply it invalid information, Helm emits a warning?_

Incidentally, `kubectl` seems to model the same behavior (though not for `kubectl help`). The warning is baked into the Kubernetes libraries, and there is literally no way to shut it off. (They even ignore the log level settings when printing it.)

I would propose that the best thing to do is to `KUBECONFIG="" helm version`  if you do not have a valid configuration file.

**Comment by unguiculus** [comment]
I tested #7831. The problem persists. I still do consider this a bug. From a technical standpoint, it is unnecessary to initialize the `actionConfig` for commands like `helm version` or `helm env`, etc. IMO, these should just work. This is especially true when other tools, such as chart-testing in this case, parse the output of `helm version --short` as semver.

**Comment by scottrigby** [comment]
I'm also coming at this from automation tools like chart-testing and the helm github actions.

I liked the direction for a fix @mattfarina @anshulvermapatel and @marckhouzam discussed. I understand the workaround in the meantime in https://github.com/helm/helm/issues/7796#issuecomment-602816914 but – my 2¢ here – not sure this can be considered fixed until commands that don't need KUBECONFIG stop trying to find it 🤔

**Comment by anshulvermapatel** [comment]
I agree with @scottrigby , well, anyways, discuss this, do let me k now, I can create a PR based on [ this comment](https://github.com/helm/helm/issues/7796#issuecomment-607510369) and am open to discuss this further.

**Comment by marckhouzam** [comment]
Personally I'm not a fan of the map solution.  It is hard to maintain and prone to errors.  Imagine for example a simple typo in the name of a command within the map: the real command would actually stop working because it would not get the config client anymore.

**Comment by anshulvermapatel** [comment]
@marckhouzam , well I think these commands are not too much in numbers so it is less prune to errors. Once we test them thoroughly, I think we can avoid initializing actionConfig where it is not required.

**Comment by technosophos** [comment]
The suggested fix by @anshulvermapatel is the only approach @adamreese and I have vetted as possible. We have uncovered a bug in Kubernetes itself that prevents suppressing the error using the normal means.

While I cannot justify calling this a bug, if you all insist this is something that must be fixed, there currently is no other way until Kubernetes gets its ship in order.

**Comment by anshulvermapatel** [comment]
@technosophos , well, it is going to get solved in Kubernetes, then I don't think this is harming someone until Kubernetes gets its ship in order. We can wait till then and have this message as is, as it does not stops the work.

**Comment by technosophos** [comment]
If it is going to get fixed in k8s, we should drop a link in here to the issue/PR.

**Comment by bridgetkromhout** [comment]
Hi, @unguiculus! It appears this is [fixed as of Kubernetes 1.18](https://github.com/kubernetes/kubectl/issues/853).

Here is how I tested after renaming my `~/kube`:

$ kubectl version --client=true
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
$ kubectl version
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
$ helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
$ helm version --short
v3.3.3+g55e3ca0
$

**Comment by bridgetkromhout** [comment]
Ah, that said, this test case still produces an error:
```
$ KUBECONFIG=config-does-not-exist helm version
W0919 17:01:06.751661   47624 loader.go:223] Config not found: config-does-not-exist
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Perhaps now that it's fixed in Kubernetes there is a path forward. More investigation is warranted.

**Comment by thomastvedt** [comment]
This is still not fixed right? I'm still getting the warning anyway
