### ISSUE TITLE
helm lint: Schema validation ignoring options

### ISSUE THREAD

**Issue by Ulminator** [helm/helm#8267]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Local minikube

I have noticed that `helm lint` is ignoring additional options I am providing so that it passes schema validation. I have created a simple `lint-values.yaml` file that looks like so:

```yaml
postgres:
  password: foo
```

In my `values.yaml` file `postgres.password` is set to `null`.

I am passing in the file as an arg like so:

```
helm lint chart-dir/ -f lint-values.yaml
```

Which gives me this error:

```
[ERROR] values.yaml: - postgres.password: Invalid type. Expected: string, given: null


Error: 1 chart(s) linted, 1 chart(s) failed
```

This issue also seems to be present when just providing `--set/--set-string` as well with `helm lint`. Interestingly enough, `helm template chart-dir/ -f lint-values.yaml` works and does not give me the schema validation error.

**Comment by mattfarina** [comment]
I believe this is fixed by #7984 which is currently scheduled to be part of the v3.3.0 release.

**Comment by bacongobbler** [comment]
@Ulminator can you please test using the canaries and verify this issue has been fixed in master for you?

**Comment by bacongobbler** [comment]
ref: https://helm.sh/docs/intro/install/#from-canary-builds

**Comment by Ulminator** [comment]
I tried with the canary release and the issue still seems to persist for me.

helm version: 
```
version.BuildInfo{Version:"v3.2+unreleased", GitCommit:"e09e8604e6160775890c154b1fb8b6683a8bbb6f", GitTreeState:"clean", GoVersion:"go1.14.4"}
```

`helm lint chart-dir/` output:

```
==> Linting chart-dir/release-name
[ERROR] values.yaml: - postgres.password: Invalid type. Expected: string, given: null

[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
release-name:
- postgres: password is required
```

`helm lint chart-dir/ -f lint-values.yaml` output:

```
==> Linting chart-dir/release-name
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - postgres: password is required


Error: 1 chart(s) linted, 1 chart(s) failed
```

Here is my `values.schema.json`:
```json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "properties": {
        "postgres": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
            },
            "required": [
                "password"
            ]
        }
    }
}
```

When I remove the `required` array the issue seems to be resolved, but the only thing enforcing that `postgres.password` is provided is the fact that the schema specifies a `string` and the default value is `null` in the `values.yaml`:

```
[ERROR] templates/: template: release-name/templates/configs.yaml:38:57: executing "release-name/templates/configs.yaml" at <b64enc>: invalid value; expected string
```

It looks like the `required` check with the schema runs before the values are provided are applied?

**Comment by Cweiping** [comment]
`helm lint` has two levels of errors, warnings and errors. Warnings by default do not count as failures. You can use `--strict` to force verification.

**Comment by abdennour** [comment]
What's the solution for this issue ?

**Comment by BradleyBoutcher** [comment]
I'm still encountering this error on Helm 3.5.3
Schema: 
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "conjur": {
      "properties": {
        "account": {
          "type": "string"
        },
        "applianceUrl": {
          "type": "string"
        },
        "ssl": {
          "oneOf": [
            {
              "required": [
                "certificateFilePath"
              ]
            },
            {
              "required": [
                "certificateBase64"
              ]
            }
          ],
          "properties": {
            "certificateFilePath": {
              "type": "string",
              "minLength": 1,
              "regex": "(^files\/(.*))|(^tests\/(.*))"
            },
            "certificateBase64": {
              "type": "string",
              "minLength": 1,
              "regex": "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
            }
          }
        }
      }
   }
}
```

However, when I use `helm lint . --set <somekey>:<somevalue>`, the linter only respects the `somekey`, but does not recognize the `somevalue`.
