### ISSUE TITLE
Helm does not error on typo or missing sub-command

### ISSUE THREAD

**Issue by Michael-Sinz** [helm/helm#8268]
Output of `helm version`: version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

Output of `kubectl version`: n/a 

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

When issuing a helm command, helm returns success on typos.

For example "helm repo sadd foo https://foo/bar" will show the help for "helm repo" but exit code will be 0 (success) rather than non-zero (failure)

This prevents tools from correctly identifying an error happened.

The fix for cobra command line parsing to correctly fix the problem they had is in https://github.com/spf13/cobra/pull/922 and has been in master for over half a year now.

Could we please get helm to fix this.

(This would also then match most commands that fail when typos or missing sub-commands are given.)

Note that git acts correctly - it will provide help if you mistype a command but it will be an error unless you specifically asked for help.

For example, just "git" shows the help but has an exit code of non-zero (1).  But "git --help" shows the help with an exit code of 0 (success) in that it did what you asked it to.

**Comment by bacongobbler** [comment]
Helm 3.2.3 uses [cobra 1.0.0](https://github.com/helm/helm/blob/8ea6b970ecd02365a230420692350057d48278e5/go.mod#L32), which should contain the fix. cobra 1.0 was released in April. That PR you linked to appears to have been merged in August 2019, so it should be in the 1.0 release.

If you can pinpoint where in the codebase that may be causing the issue, we'd appreciate the help.

**Comment by mattfarina** [comment]
I've replicated the issue on the tip of master which runs cobra 1.0.0. Any pointers to what's causing the issue or pull requests with a fix are welcome.

**Comment by wawa0210** [comment]
If allowed, I can understand the problem and try to fix it

**Comment by bacongobbler** [comment]
feel free

**Comment by marckhouzam** [comment]
> The fix for cobra command line parsing to correctly fix the problem they had is in spf13/cobra#922 and has been in master for over half a year now.

The Cobra fix in question was reverted in https://github.com/spf13/cobra/pull/1068.
I haven't dug into it further, but it explains why helm is behaving the way it is.

**Comment by mattfarina** [comment]
This is now fixed on the tip of master so I'm going to close the issue.

**Comment by marckhouzam** [comment]
> This is now fixed on the tip of master so I'm going to close the issue.

@mattfarina Is this really fixed on master or was there a mixup in which issue you mean to close?

**Comment by marckhouzam** [comment]
After speaking at the helm dev call, we agreed to re-open if the problem could be reproduced, so:
```
$ bin/helm version
version.BuildInfo{Version:"v3.3+unreleased", GitCommit:"198f40368874abbe4dda2ff6ba3eca516932da76", GitTreeState:"clean", GoVersion:"go1.15"}
$ bin/helm repo sadd foo https://foo/bar  &>/dev/null && echo "No error" || echo "With error"
No error
```
As we can see an invalid command below `helm repo` still does not generate an error.
There is a PR in Cobra for this but I had some backwards-compatibility concerns which are waiting for opinions from the Cobra maintainers: https://github.com/spf13/cobra/pull/1157
