### ISSUE TITLE
Nested `null` values do not remove keys from sub-charts

### ISSUE THREAD

**Issue by elliotkennedy** [helm/helm#9136]
#2648 and #5184 allow for deletion of keys by setting null values in a values.yaml file. However it doesn't work for removing nested values in sub-charts, e.g.:

values.yaml:

```yaml
kibana:
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: null
      memory: 2Gi
```

Chart.yaml:
```yaml
apiVersion: v2
name: elastic
description: Elastic stack
type: application
version: 0.0.1
dependencies:
  - name: kibana
    version: 7.9.3
    repository: "@elastic"
```

Results in a deployment object with the base cpu limits:
```yaml
...
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi

```

Output of `helm version`:

```bash
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:

```bash
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-12-04T15:20:33Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS/Kops

**Comment by Chili-Man** [comment]
I've been running into this same exact issue with Helm version 3.2, 3.3, and 3.4 as well. I haven't found a good workaround to this issue yet;

**Comment by elliotkennedy** [comment]
I believe there are 2 similar issues preventing this from working, modifiying the chart object makes calls to CoalesceValues non-idempotent:

1) [See here](https://github.com/helm/helm/blob/master/pkg/chartutil/dependencies.go#L271) - The call to dependencies.processImportValues is overwriting the null values in the subchart so subsequent calls to CoalesceValues do not remove the default key.

2) [See here](https://github.com/helm/helm/blob/master/pkg/chartutil/coalesce.go#L173) - The reference to the value is copied directly to the values map, subsequent modifications of this object are applied to the chart, so subsequent calls to CoalesceValues do not remove the default key

**Comment by wrdls** [comment]
@mattfarina In case you need an easy reproducible case for this bug the be labeled as `confirmed`:

I'm having the same issue with the [Bitnami Redis](https://github.com/bitnami/charts/tree/master/bitnami/redis) chart when trying to set the [`podDisruptionBudget.maxUnavailable` ](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L831) key. For this to work you need to  be able to unset the `minAvailable` key as it's otherwise not a valid PDB spec.

So with a parent chart like this:

Chart.yaml
```yaml
apiVersion: v2
name: redis
version: 0.0.1
dependencies:
  - name: redis
    version: 10.7.16
    repository: https://charts.bitnami.com/bitnami
```

values.yaml
```yaml
redis:
  podDisruptionBudget:
    enabled: true
    minAvailable: null    # THIS DOES NOT WORK
    maxUnavailable: 1
```

Output:
```shell
% helm template redis . -s charts/redis/templates/pdb.yaml | kubectl apply --dry-run=server -f -
The PodDisruptionBudget "redis" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc038134280), Selector:(*v1.LabelSelector)(0xc0381342a0), MaxUnavailable:(*intstr.IntOrString)(0xc0381342e0)}: minAvailable and maxUnavailable cannot be both set
```

Versions used:
```shell
% helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.15.6"}
% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.6000", GitCommit:"b02f5ea6726390a4b19d06fa9022981750af2bbc", GitTreeState:"clean", BuildDate:"2020-11-18T09:16:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bappr** [comment]
Confirm. I am getting the same issue with my helm chart https://github.com/kintoproj/kinto-helm
Right now, the only workaround I found is to pass it as a `--set` parameter. Pretty annoying.

**Comment by karolinepauls** [comment]
Reproduction here: https://github.com/karolinepauls/helm-unset-dep-value-bug-repro - you can use it co confirm the issue, since it's now unconfirmed.




Relates to https://github.com/helm/helm/issues/1966.

**Comment by scott-grimes** [comment]
same issue with a library chart (ala https://helm.sh/docs/topics/library_charts/ ). we have a deployment template library template that we then override. the default is to use a RollingUpdate, but if we want to replace that with a "Recreate" it's impossible to remove the spec.strategy.rollingUpdate field present in the `_deployment.tpl` definition

```
# _deployment.tpl
{{- define "library.deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
...
{{- end -}}
{{- define "library.deployment" -}}
{{- template "library.util.merge" (append . "library.deployment.tpl") -}}
{{- end -}}
```

```
# deployment_a.yaml
{{- define "app.deployment.a" -}}
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
```

this still renders to 
```
spec:
  strategy:
    type: Recreate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
```

**Comment by luckoseabraham** [comment]
@mattfarina  - Can you remove the unconfirmed label from this issue. This can be easily reproducible. This issue exists even in 3.5.2. The label paints a wrong picture about the issue.

Apparently #6080 was supposed to fix it. And this was supposed to be ported over to v3 as well with #5781 Unfortunately the issue is back.

**Comment by alecrajeev** [comment]
I've also verified this is still an issue in helm version 3.5.3

**Comment by AmundsenJunior** [comment]
Can confirm this on helm 3.4.2, with the finding that setting `livenessProbe.httpGet` to `null` in the `values.yaml` of the subchart does nothing to null out that configuration. But I use helm-secrets, which requires including `-f secrets.yaml` in any `helm install` operation, and including the null-set value in that file is successful, much like a `--set` command line override successfully nulls that config.

**Comment by scott-grimes** [comment]
for those using flux to sync helmreleases there is no workaround unfortunately at the moment

**Comment by pisto** [comment]
Looking at this.

**Comment by MatteoInfi** [comment]
not sure it is related to this bug, but when I unset using empty value it will not work either.

```
mysubchart1:
    ingress:
      hostname:
```

First the empty value is not retained, so I will need to override it again, but that will not work

```
subchart2:
  mysubchart1:
    ingress:
      hostname: <==== this will not work as the one above
```

**Comment by ShuzZzle** [comment]
Same problem with helm 3.6.0. Any update on this matter?

**Comment by AlexanderKholodov46** [comment]
Still the same problem in Helm 3.7.0

**Comment by pmorch** [comment]
@giselleserate-okta  writes:

> My current workaround is to reassert the `values.yaml` file in my helm command with `-f ./values.yaml`, but this is a bit unwieldy.

Could you explain a little more how that workaround works? Do you reassert the `values.yaml` from the subchart somehow? I've tried various `-f` combinations without success...

**Comment by giselleserate-okta** [comment]
@pmorch sorry, it's been a sec since I've been working on this. As I recall, the subchart inheritance specifically is the part that doesn't work. If you instead manually set a field to null either with a `--set` flag or a `-f` flag in the helm install command, it _does_ work. 

If you want to write your values.yaml as if this bug doesn't exist, and then just include `-f values.yaml` in all your helm install commands, that would be the workaround. 

Quoting a comment above:
> Can confirm this on helm 3.4.2, with the finding that setting `livenessProbe.httpGet` to `null` in the `values.yaml` of the subchart does nothing to null out that configuration. But I use helm-secrets, which requires including `-f secrets.yaml` in any `helm install` operation, and including the null-set value in that file is successful, much like a `--set` command line override successfully nulls that config.

**Comment by yahel2410** [comment]
I had an issue similar to that of @scott-grimes, trying to remove the `spec.strategy.rollingUpdate` key.
I ended up writing this helper function:
```
{{ define "my-service.strategy" -}}
type: {{ .Values.strategy.type }}

{{- if eq .Values.strategy.type "RollingUpdate" }}
rollingUpdate:
{{- toYaml .Values.strategy.rollingUpdate | nindent 2 }}

{{- end }}
{{- end }}
```
Then in `deployment.yaml` template
```
apiVersion: apps/v1
kind: Deployment
spec:
  strategy:
    {{- include "my-service.strategy" . | nindent 4 }}
...
```

**Comment by turowicz** [comment]
This issue is such pain in the ass. Please fix it asap.

**Comment by djmcgreal-cc** [comment]
I think that it's not necessarily the _inheritence_ that's the problem, but that the `null` needs to be set in two separate contexts. I moved my entire `readinessProbe` override to another _values.yaml_ but it still wouldn't remove the default `httpGet`.

**Comment by ryancastle** [comment]
This is still present in 3.7.1. Using `false` works in some contexts.

```
argo-cd:
  redis:
    securityContext: false
```

**Comment by signaleleven** [comment]
> This is still present in 3.7.1. Using `false` works in some contexts.

Please check your chart to see if it makes sense. But in my case, "false" was enough to disable a "if" clause and this was a good workaround for me. YMMV.
Thank you "@ryancastle, 4 hours ago." I'm glad I searched for this now,and not this morning. :)

**Comment by ryancastle** [comment]
For the general pattern like this, using `false` works, although Helm complains about replacing a table with a boolean. 
```
      {{- if .Values.redis.securityContext }}
      securityContext: {{- toYaml .Values.redis.securityContext | nindent 8 }}
      {{- end }}
```

Helm says it "cannot" replace the table, but ultimately does.

> warning: cannot overwrite table with non table ...

### Some Workarounds
1. Use `false` instead of `~`, `null` or _empty_
2. Remove dependencies from _Chart.yaml_ after installing them into `charts` directory (although you may then have issues with sub-chart dependency conditions)
3. Explicitly reference parent chart _values.yaml_ e.g. `helm install NAME CHART -f CHART/values.yaml` (even though it should be redundant)
4. Use `--set subchart.nested.value=false`(although 3 is probably generally better)

**Comment by ryancastle** [comment]
I went back through all the Helm 3 version to confirm the behavior in each version. It wasn't clear to me if this was a one-off change, or a number of fixes and regressions with changing semantics. I didn't check RC, beta or alpha releases.

## Test

Confirm removal of values in a subchart defined in _Chart.yaml_ dependencies from inside a parent chart. 

Specifically, the _expected behavior_ tested is the ability to override a map or scalar referenced in a subchart with a null value in the parent chart.

## Summary

It seems to have been a problem since Helm 3.2.0 - which folks have previously suggested. 

## Notes

In early versions (v3.0.0-v3.1.3) Helm would behave as expected when replacing maps with null, although it would render a warning `coalesce.go:196: warning: cannot overwrite table with non table for <VALUE>`. Replacing scalars with a null value worked correctly with no errors.

In versions since v3.2.0, removing neither maps nor scalars works as expected. Using other falsy scalar values works as expected, but isn't always appropriate depending on the specific subchart.

### Example: Child chart

```
# templates/deployment.yaml
{{- if .Values.securityContext }}
securityContext: {{- toYaml .Values.securityContext | nindent 2 }}
{{- end }}
```

```
# values.yaml
securityContext:
  runAsUser: 999
```

### Example: Parent chart

```
# Chart.yaml
dependencies:
  - name: subchart
    version: "0.1.0"
```

```
# values.yaml
subchart:
  securityContext: ~
```

## Outcome
| Version | Behavior |
| --- | --- |
| v3.7.2 | Unexpected |
| v3.7.1 | Unexpected |
| v3.7.0 | Unexpected |
| v3.6.3 | Unexpected |
| v3.6.2 | Unexpected |
| v3.6.1 | Unexpected |
| v3.6.0 | Unexpected |
| v3.5.4 | Unexpected |
| v3.5.3 | Unexpected |
| v3.5.2 | Unexpected |
| v3.5.1 | Unexpected |
| v3.5.0 | Unexpected |
| v3.4.2 | Unexpected |
| v3.4.1 | Unexpected |
| v3.4.0 | Unexpected |
| v3.3.4 | Unexpected |
| v3.3.3 | Unexpected |
| v3.3.2 | Unexpected |
| v3.3.1 | Unexpected |
| v3.3.0 | Unexpected |
| v3.2.4 | Unexpected |
| v3.2.3 | Unexpected |
| v3.2.2 | Unexpected |
| v3.2.1 | Unexpected |
| v3.2.0 | Unexpected |
| v3.1.3 | Expected |
| v3.1.2 | Expected |
| v3.1.1 | Expected |
| v3.1.0 | Expected |
| v3.0.3 | Expected |
| v3.0.2 | Expected |
| v3.0.1 | Expected |
| v3.0.0 | Expected |

**Comment by PrayagS** [comment]
Any updates on this issue?

I'm trying to install an application via ArgoCD and I'm listing the application's chart as a dependency i.e. subchart. As expected, ArgoCD doesn't translate the `livenessProbe: {}` present in the subchart's values because of this issue.

**Comment by stephenpope** [comment]
Also struggling with this with a sub-chart (trying to remove/null-out a `readinessProbe.tcpSocket` to replace with `readinessProbe.exec`) .. in Helm `v3.8.1`.

Will now need to fork the chart :(

**Comment by nathanjrobertson** [comment]
> Also struggling with this with a sub-chart (trying to remove/null-out a `readinessProbe.tcpSocket` to replace with `readinessProbe.exec`) .. in Helm `v3.8.1`.
> 
> Will now need to fork the chart :(

I'm working around it currently by always specifying "-f values.yaml" on the command line. So that I don't forget, I have a wrapper shell script to run helm with.

**Comment by vliska** [comment]
> 

That workaround does not work in most of the cases we need (like trying to set null to securityContext in bitnami charts because of openshift).

**Comment by RytisLT** [comment]
> for those using flux to sync helmreleases there is no workaround unfortunately at the moment

I've managed to work-around the issue using postRederers. I've removed unwanted `volumeClaimTemplates` like this:

    postRenderers:
      - kustomize:
          patchesJson6902:
            - target:
                group: apps
                version: v1
                kind: StatefulSet
                name: filerun-v1-mariadb
              patch:
                - op: remove
                  path: /spec/volumeClaimTemplates

**Comment by turowicz** [comment]
@RytisLT is this available to vanilla Helm or do we need to use Flux?

**Comment by RytisLT** [comment]
@turowicz I used flux, but you can achieve something similar with Helm + Kustomize: https://helm.sh/docs/topics/advanced/

**Comment by turowicz** [comment]
I just use a sed as a step pre release that modifies the subchart by unpacking it, deleting the values and packing it back :D

**Comment by nazarewk** [comment]
I'm not 100% sure this is the same issue, but i noticed passing `null` values work when not using `-f` at all https://gist.github.com/nazarewk/954779d56c97c2ff72b56b78096807e7

**Comment by xrow** [comment]
It would be nice if we see a fix for this issue that also exists in helm 3.9.0

This wokraround worked for me luckly....

```
# values.yaml
subchart:
  securityContext: false 
```

**Comment by foosinn** [comment]
Also ran multiple time into that issue. Would love to see a fix

Maybe yaml's type inference can be used here with a special type?

This would not break any existing `value.yaml` but allow users to empty out variables.

**Comment by Imunhatep** [comment]
How many years to wait for given PR to be merged?!

**Comment by R-Studio** [comment]
Any news on this?

**Comment by hosswald** [comment]
Still happening in v3.9.2

> This is still present in 3.7.1. Using `false` works in some contexts.
> 
> ```
> argo-cd:
>   redis:
>     securityContext: false
> ```
Confirming that this workaround works.

**Comment by clayvan** [comment]
For what it's worth I've found a possible workaround, or at least another bug but it helped me get past this.

Basically use 2 values files.

Given a default `values.yaml` in a dependent chart of:
```yaml
# values.yaml
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1
```

Overriding that with another values file like this, did NOT achieve the `null` override, and the default `1` was used.
```
# dev-values.yaml
podDisruptionBudget:
  enabled: true
  minAvailable: null
  maxUnavailable: 1
```

But when I had a 2nd values override file passed into helm it worked.
```
# dev-further-override-values.yaml
podDisruptionBudget:
  enabled: true
  minAvailable: null
  maxUnavailable: 1
```

No idea why this behavior would be any different, and this is with ArgoCD `v2.4.3` which i believe used Helm `v3.8.1`.

**Comment by aabouzaid** [comment]
@clayvan could you please write the exact steps to reproduce the workaround you mentioned?

I was not able to reproduce it, neither with Helm `v3.8.1` nor `v3.9.2` (latest).

**Comment by sd-matt-b** [comment]
> It would be nice if we see a fix for this issue that also exists in helm 3.9.0
> 
> This wokraround worked for me luckly....
> 
> ```
> # values.yaml
> subchart:
>   securityContext: false 
> ```
> 
> and ...
> 
> it doen`t work if the subchart has a schema json.... :-(

This worked for me, notably changing `maxUnavailable` from `null` to `false` like so:

```
  podDisruptionBudget:
    minAvailable: "0"
    maxUnavailable: false
```

Thank you!

**Comment by JuryA** [comment]
Any progress on this? I still facing this stupid bug and workarounds are a really bad habit. Assigning `false` instead of `null` is working, but still getting `coalesce.go:220: warning: cannot overwrite table with non table for ...` I think that this bug is a really critical one because it's confusing people and I wonder why it cannot be fixed? Thank you for reply...

**Comment by albgus** [comment]
Assigning `false` is not a workaround, it just passes the false value through to the resource. I guess that might work sometimes, but otherwise it'll just fail ex: `got "boolean", expected "map"`

Helm v3.9.3

**Comment by JuryA** [comment]
> Assigning `false` is not a workaround...

Okay, better call it "pseudo-workaround", but my question is: Is it the only solution to solve the problem of not being able to unset (means set to null) the value in the sub-chart from the parent chart in globals?

**Comment by eduardobr** [comment]
This is quite critical... Just thinking about the massive number of workarounds and pseudo properties to control what's rendered just because it doesn't work

**Comment by joejulian** [comment]
Happy to have a contribution to address this. Probably should start with a [HIP](https://github.com/helm/community/blob/main/hips/hip-0001.md) also take a look at the [contributing](https://github.com/helm/helm/blob/main/CONTRIBUTING.md) doc.

**Comment by LoicGombeaud** [comment]
I just ran into this issue, and would very much appreciate a fix.

**Comment by jamoflaw** [comment]
@joejulian - I believe https://github.com/helm/helm/pull/11440 should fix this bug - looks like an bug where null keys are preemptively removed before subcharts are processed which causes the subcharts to merge their keys back into the parent chart again.

**Comment by igorzamyslov** [comment]
It seems to be a duplicate of #9027

**Comment by jamoflaw** [comment]
> It seems to be a duplicate of #9027

Yeah I'd agree - looks like the behaviour I replicated in that PR, it should resolve that issue too

**Comment by joejulian** [comment]
Closing this one. Let's continue to track this in #9027. Thanks!

**Comment by rodrigoechaide** [comment]
I have created a new [issue](https://github.com/helm/helm/issues/12637) because this problem persists in the latest version of Kubernetes.
